//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/apache/commons/collections15/BufferUtils.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "org/apache/commons/collections15/ArrayStack.h"
#include "org/apache/commons/collections15/Buffer.h"
#include "org/apache/commons/collections15/BufferUtils.h"
#include "org/apache/commons/collections15/Predicate.h"
#include "org/apache/commons/collections15/Transformer.h"
#include "org/apache/commons/collections15/buffer/BlockingBuffer.h"
#include "org/apache/commons/collections15/buffer/PredicatedBuffer.h"
#include "org/apache/commons/collections15/buffer/SynchronizedBuffer.h"
#include "org/apache/commons/collections15/buffer/TransformedBuffer.h"
#include "org/apache/commons/collections15/buffer/TypedBuffer.h"
#include "org/apache/commons/collections15/buffer/UnmodifiableBuffer.h"

J2OBJC_INITIALIZED_DEFN(OrgApacheCommonsCollections15BufferUtils)

id<OrgApacheCommonsCollections15Buffer> OrgApacheCommonsCollections15BufferUtils_EMPTY_BUFFER_;

@implementation OrgApacheCommonsCollections15BufferUtils

- (instancetype)init {
  OrgApacheCommonsCollections15BufferUtils_init(self);
  return self;
}

+ (id<OrgApacheCommonsCollections15Buffer>)synchronizedBufferWithOrgApacheCommonsCollections15Buffer:(id<OrgApacheCommonsCollections15Buffer>)buffer {
  return OrgApacheCommonsCollections15BufferUtils_synchronizedBufferWithOrgApacheCommonsCollections15Buffer_(buffer);
}

+ (id<OrgApacheCommonsCollections15Buffer>)blockingBufferWithOrgApacheCommonsCollections15Buffer:(id<OrgApacheCommonsCollections15Buffer>)buffer {
  return OrgApacheCommonsCollections15BufferUtils_blockingBufferWithOrgApacheCommonsCollections15Buffer_(buffer);
}

+ (id<OrgApacheCommonsCollections15Buffer>)unmodifiableBufferWithOrgApacheCommonsCollections15Buffer:(id<OrgApacheCommonsCollections15Buffer>)buffer {
  return OrgApacheCommonsCollections15BufferUtils_unmodifiableBufferWithOrgApacheCommonsCollections15Buffer_(buffer);
}

+ (id<OrgApacheCommonsCollections15Buffer>)predicatedBufferWithOrgApacheCommonsCollections15Buffer:(id<OrgApacheCommonsCollections15Buffer>)buffer
                                                        withOrgApacheCommonsCollections15Predicate:(id<OrgApacheCommonsCollections15Predicate>)predicate {
  return OrgApacheCommonsCollections15BufferUtils_predicatedBufferWithOrgApacheCommonsCollections15Buffer_withOrgApacheCommonsCollections15Predicate_(buffer, predicate);
}

+ (id<OrgApacheCommonsCollections15Buffer>)typedBufferWithOrgApacheCommonsCollections15Buffer:(id<OrgApacheCommonsCollections15Buffer>)buffer
                                                                                 withIOSClass:(IOSClass *)type {
  return OrgApacheCommonsCollections15BufferUtils_typedBufferWithOrgApacheCommonsCollections15Buffer_withIOSClass_(buffer, type);
}

+ (id<OrgApacheCommonsCollections15Buffer>)transformedBufferWithOrgApacheCommonsCollections15Buffer:(id<OrgApacheCommonsCollections15Buffer>)buffer
                                                       withOrgApacheCommonsCollections15Transformer:(id<OrgApacheCommonsCollections15Transformer>)transformer {
  return OrgApacheCommonsCollections15BufferUtils_transformedBufferWithOrgApacheCommonsCollections15Buffer_withOrgApacheCommonsCollections15Transformer_(buffer, transformer);
}

+ (void)initialize {
  if (self == [OrgApacheCommonsCollections15BufferUtils class]) {
    OrgApacheCommonsCollections15BufferUtils_EMPTY_BUFFER_ = OrgApacheCommonsCollections15BufferUnmodifiableBuffer_decorateWithOrgApacheCommonsCollections15Buffer_(new_OrgApacheCommonsCollections15ArrayStack_initWithInt_(1));
    J2OBJC_SET_INITIALIZED(OrgApacheCommonsCollections15BufferUtils)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "BufferUtils", NULL, 0x1, NULL, NULL },
    { "synchronizedBufferWithOrgApacheCommonsCollections15Buffer:", "synchronizedBuffer", "Lorg.apache.commons.collections15.Buffer;", 0x9, NULL, "<E:Ljava/lang/Object;>(Lorg/apache/commons/collections15/Buffer<TE;>;)Lorg/apache/commons/collections15/Buffer<TE;>;" },
    { "blockingBufferWithOrgApacheCommonsCollections15Buffer:", "blockingBuffer", "Lorg.apache.commons.collections15.Buffer;", 0x9, NULL, "<E:Ljava/lang/Object;>(Lorg/apache/commons/collections15/Buffer<TE;>;)Lorg/apache/commons/collections15/Buffer<TE;>;" },
    { "unmodifiableBufferWithOrgApacheCommonsCollections15Buffer:", "unmodifiableBuffer", "Lorg.apache.commons.collections15.Buffer;", 0x9, NULL, "<E:Ljava/lang/Object;>(Lorg/apache/commons/collections15/Buffer<TE;>;)Lorg/apache/commons/collections15/Buffer<TE;>;" },
    { "predicatedBufferWithOrgApacheCommonsCollections15Buffer:withOrgApacheCommonsCollections15Predicate:", "predicatedBuffer", "Lorg.apache.commons.collections15.Buffer;", 0x9, NULL, "<E:Ljava/lang/Object;>(Lorg/apache/commons/collections15/Buffer<TE;>;Lorg/apache/commons/collections15/Predicate<TE;>;)Lorg/apache/commons/collections15/Buffer<TE;>;" },
    { "typedBufferWithOrgApacheCommonsCollections15Buffer:withIOSClass:", "typedBuffer", "Lorg.apache.commons.collections15.Buffer;", 0x9, NULL, "<E:Ljava/lang/Object;>(Lorg/apache/commons/collections15/Buffer<TE;>;Ljava/lang/Class<TE;>;)Lorg/apache/commons/collections15/Buffer<TE;>;" },
    { "transformedBufferWithOrgApacheCommonsCollections15Buffer:withOrgApacheCommonsCollections15Transformer:", "transformedBuffer", "Lorg.apache.commons.collections15.Buffer;", 0x9, NULL, "<I:Ljava/lang/Object;O:Ljava/lang/Object;>(Lorg/apache/commons/collections15/Buffer<TI;>;Lorg/apache/commons/collections15/Transformer<TI;TO;>;)Lorg/apache/commons/collections15/Buffer<TO;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "EMPTY_BUFFER_", NULL, 0x19, "Lorg.apache.commons.collections15.Buffer;", &OrgApacheCommonsCollections15BufferUtils_EMPTY_BUFFER_, NULL,  },
  };
  static const J2ObjcClassInfo _OrgApacheCommonsCollections15BufferUtils = { 2, "BufferUtils", "org.apache.commons.collections15", NULL, 0x1, 7, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheCommonsCollections15BufferUtils;
}

@end

void OrgApacheCommonsCollections15BufferUtils_init(OrgApacheCommonsCollections15BufferUtils *self) {
  (void) NSObject_init(self);
}

OrgApacheCommonsCollections15BufferUtils *new_OrgApacheCommonsCollections15BufferUtils_init() {
  OrgApacheCommonsCollections15BufferUtils *self = [OrgApacheCommonsCollections15BufferUtils alloc];
  OrgApacheCommonsCollections15BufferUtils_init(self);
  return self;
}

id<OrgApacheCommonsCollections15Buffer> OrgApacheCommonsCollections15BufferUtils_synchronizedBufferWithOrgApacheCommonsCollections15Buffer_(id<OrgApacheCommonsCollections15Buffer> buffer) {
  OrgApacheCommonsCollections15BufferUtils_initialize();
  return OrgApacheCommonsCollections15BufferSynchronizedBuffer_decorateWithOrgApacheCommonsCollections15Buffer_(buffer);
}

id<OrgApacheCommonsCollections15Buffer> OrgApacheCommonsCollections15BufferUtils_blockingBufferWithOrgApacheCommonsCollections15Buffer_(id<OrgApacheCommonsCollections15Buffer> buffer) {
  OrgApacheCommonsCollections15BufferUtils_initialize();
  return OrgApacheCommonsCollections15BufferBlockingBuffer_decorateWithOrgApacheCommonsCollections15Buffer_(buffer);
}

id<OrgApacheCommonsCollections15Buffer> OrgApacheCommonsCollections15BufferUtils_unmodifiableBufferWithOrgApacheCommonsCollections15Buffer_(id<OrgApacheCommonsCollections15Buffer> buffer) {
  OrgApacheCommonsCollections15BufferUtils_initialize();
  return OrgApacheCommonsCollections15BufferUnmodifiableBuffer_decorateWithOrgApacheCommonsCollections15Buffer_(buffer);
}

id<OrgApacheCommonsCollections15Buffer> OrgApacheCommonsCollections15BufferUtils_predicatedBufferWithOrgApacheCommonsCollections15Buffer_withOrgApacheCommonsCollections15Predicate_(id<OrgApacheCommonsCollections15Buffer> buffer, id<OrgApacheCommonsCollections15Predicate> predicate) {
  OrgApacheCommonsCollections15BufferUtils_initialize();
  return OrgApacheCommonsCollections15BufferPredicatedBuffer_decorateWithOrgApacheCommonsCollections15Buffer_withOrgApacheCommonsCollections15Predicate_(buffer, predicate);
}

id<OrgApacheCommonsCollections15Buffer> OrgApacheCommonsCollections15BufferUtils_typedBufferWithOrgApacheCommonsCollections15Buffer_withIOSClass_(id<OrgApacheCommonsCollections15Buffer> buffer, IOSClass *type) {
  OrgApacheCommonsCollections15BufferUtils_initialize();
  return OrgApacheCommonsCollections15BufferTypedBuffer_decorateWithOrgApacheCommonsCollections15Buffer_withIOSClass_(buffer, type);
}

id<OrgApacheCommonsCollections15Buffer> OrgApacheCommonsCollections15BufferUtils_transformedBufferWithOrgApacheCommonsCollections15Buffer_withOrgApacheCommonsCollections15Transformer_(id<OrgApacheCommonsCollections15Buffer> buffer, id<OrgApacheCommonsCollections15Transformer> transformer) {
  OrgApacheCommonsCollections15BufferUtils_initialize();
  return OrgApacheCommonsCollections15BufferTransformedBuffer_decorateWithOrgApacheCommonsCollections15Buffer_withOrgApacheCommonsCollections15Transformer_(buffer, transformer);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheCommonsCollections15BufferUtils)
