//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeogebraiOS/GeogebraiOS/sources/org/apache/commons/collections15/iterators/UniqueFilterIterator.java
//

#ifndef _OrgApacheCommonsCollections15IteratorsUniqueFilterIterator_H_
#define _OrgApacheCommonsCollections15IteratorsUniqueFilterIterator_H_

#include "J2ObjC_header.h"
#include "org/apache/commons/collections15/iterators/FilterIterator.h"

@protocol JavaUtilIterator;

@interface OrgApacheCommonsCollections15IteratorsUniqueFilterIterator : OrgApacheCommonsCollections15IteratorsFilterIterator

#pragma mark Public

- (instancetype)initWithJavaUtilIterator:(id<JavaUtilIterator>)iterator;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsCollections15IteratorsUniqueFilterIterator)

FOUNDATION_EXPORT void OrgApacheCommonsCollections15IteratorsUniqueFilterIterator_initWithJavaUtilIterator_(OrgApacheCommonsCollections15IteratorsUniqueFilterIterator *self, id<JavaUtilIterator> iterator);

FOUNDATION_EXPORT OrgApacheCommonsCollections15IteratorsUniqueFilterIterator *new_OrgApacheCommonsCollections15IteratorsUniqueFilterIterator_initWithJavaUtilIterator_(id<JavaUtilIterator> iterator) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsCollections15IteratorsUniqueFilterIterator)

#endif // _OrgApacheCommonsCollections15IteratorsUniqueFilterIterator_H_
