//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/geogebra/common/kernel/locusequ/arith/EquationUnaryOperator.java
//

#ifndef _OrgGeogebraCommonKernelLocusequArithEquationUnaryOperator_H_
#define _OrgGeogebraCommonKernelLocusequArithEquationUnaryOperator_H_

#include "J2ObjC_header.h"
#include "org/geogebra/common/kernel/locusequ/arith/EquationOperator.h"

@class OrgGeogebraCommonKernelLocusequArithEquationExpression;

@interface OrgGeogebraCommonKernelLocusequArithEquationUnaryOperator : OrgGeogebraCommonKernelLocusequArithEquationOperator

#pragma mark Public

- (instancetype)initWithOrgGeogebraCommonKernelLocusequArithEquationExpression:(OrgGeogebraCommonKernelLocusequArithEquationExpression *)expression;

- (OrgGeogebraCommonKernelLocusequArithEquationExpression *)getOriginalExpression;

#pragma mark Protected

- (jdouble)computeValueImpl;

- (jboolean)containsSymbolicValuesImpl;

- (jdouble)operationWithDouble:(jdouble)a;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGeogebraCommonKernelLocusequArithEquationUnaryOperator)

FOUNDATION_EXPORT void OrgGeogebraCommonKernelLocusequArithEquationUnaryOperator_initWithOrgGeogebraCommonKernelLocusequArithEquationExpression_(OrgGeogebraCommonKernelLocusequArithEquationUnaryOperator *self, OrgGeogebraCommonKernelLocusequArithEquationExpression *expression);

J2OBJC_TYPE_LITERAL_HEADER(OrgGeogebraCommonKernelLocusequArithEquationUnaryOperator)

#endif // _OrgGeogebraCommonKernelLocusequArithEquationUnaryOperator_H_
