//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/com/vividsolutions/jts/index/strtree/ItemBoundable.java
//

#ifndef _ComVividsolutionsJtsIndexStrtreeItemBoundable_H_
#define _ComVividsolutionsJtsIndexStrtreeItemBoundable_H_

#include "J2ObjC_header.h"
#include "com/vividsolutions/jts/index/strtree/Boundable.h"

@interface ComVividsolutionsJtsIndexStrtreeItemBoundable : NSObject < ComVividsolutionsJtsIndexStrtreeBoundable >

#pragma mark Public

- (instancetype)initWithId:(id)bounds
                    withId:(id)item;

- (id)getBounds;

- (id)getItem;

@end

J2OBJC_EMPTY_STATIC_INIT(ComVividsolutionsJtsIndexStrtreeItemBoundable)

FOUNDATION_EXPORT void ComVividsolutionsJtsIndexStrtreeItemBoundable_initWithId_withId_(ComVividsolutionsJtsIndexStrtreeItemBoundable *self, id bounds, id item);

FOUNDATION_EXPORT ComVividsolutionsJtsIndexStrtreeItemBoundable *new_ComVividsolutionsJtsIndexStrtreeItemBoundable_initWithId_withId_(id bounds, id item) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComVividsolutionsJtsIndexStrtreeItemBoundable)

#endif // _ComVividsolutionsJtsIndexStrtreeItemBoundable_H_
