//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeogebraiOS/GeogebraiOS/sources/org/geogebra/common/geogebra3D/kernel3D/geos/GeoCoords4D.java
//


#include "J2ObjC_source.h"
#include "org/geogebra/common/geogebra3D/kernel3D/geos/GeoCoords4D.h"

@interface OrgGeogebraCommonGeogebra3DKernel3DGeosGeoCoords4D : NSObject
@end

@implementation OrgGeogebraCommonGeogebra3DKernel3DGeosGeoCoords4D

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setCoordsWithDouble:withDouble:withDouble:withDouble:", "setCoords", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgGeogebraCommonGeogebra3DKernel3DGeosGeoCoords4D = { 2, "GeoCoords4D", "org.geogebra.common.geogebra3D.kernel3D.geos", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgGeogebraCommonGeogebra3DKernel3DGeosGeoCoords4D;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgGeogebraCommonGeogebra3DKernel3DGeosGeoCoords4D)
