//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeogebraiOS/GeogebraiOS/sources/org/geogebra/common/main/settings/ApplicationSettings.java
//

#ifndef _OrgGeogebraCommonMainSettingsApplicationSettings_H_
#define _OrgGeogebraCommonMainSettingsApplicationSettings_H_

#include "J2ObjC_header.h"
#include "org/geogebra/common/main/settings/AbstractSettings.h"

@class JavaUtilLinkedList;

@interface OrgGeogebraCommonMainSettingsApplicationSettings : OrgGeogebraCommonMainSettingsAbstractSettings

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilLinkedList:(JavaUtilLinkedList *)listeners;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGeogebraCommonMainSettingsApplicationSettings)

FOUNDATION_EXPORT void OrgGeogebraCommonMainSettingsApplicationSettings_initWithJavaUtilLinkedList_(OrgGeogebraCommonMainSettingsApplicationSettings *self, JavaUtilLinkedList *listeners);

FOUNDATION_EXPORT OrgGeogebraCommonMainSettingsApplicationSettings *new_OrgGeogebraCommonMainSettingsApplicationSettings_initWithJavaUtilLinkedList_(JavaUtilLinkedList *listeners) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgGeogebraCommonMainSettingsApplicationSettings_init(OrgGeogebraCommonMainSettingsApplicationSettings *self);

FOUNDATION_EXPORT OrgGeogebraCommonMainSettingsApplicationSettings *new_OrgGeogebraCommonMainSettingsApplicationSettings_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgGeogebraCommonMainSettingsApplicationSettings)

#endif // _OrgGeogebraCommonMainSettingsApplicationSettings_H_
