//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/edu/uci/ics/jung/algorithms/matrix/RealMatrixElementOperations.java
//

#ifndef _EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations_H_
#define _EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations_H_

#include "J2ObjC_header.h"
#include "edu/uci/ics/jung/algorithms/matrix/MatrixElementOperations.h"

@protocol JavaUtilMap;

@interface EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations : NSObject < EduUciIcsJungAlgorithmsMatrixMatrixElementOperations >

#pragma mark Public

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)edgeData;

- (NSNumber *)computePathDataWithId:(id)e1
                             withId:(id)e2;

- (id<JavaUtilMap>)getEdgeData;

- (void)mergePathsWithId:(id)e
                  withId:(id)pathData;

@end

J2OBJC_EMPTY_STATIC_INIT(EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations)

FOUNDATION_EXPORT void EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations_initWithJavaUtilMap_(EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations *self, id<JavaUtilMap> edgeData);

FOUNDATION_EXPORT EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations *new_EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations_initWithJavaUtilMap_(id<JavaUtilMap> edgeData) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations)

#endif // _EduUciIcsJungAlgorithmsMatrixRealMatrixElementOperations_H_
