//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/util/debug/SilentProfiler.java
//

#ifndef _GeogebraCommonUtilDebugSilentProfiler_H_
#define _GeogebraCommonUtilDebugSilentProfiler_H_

#include "J2ObjC_header.h"
#include "geogebra/common/util/debug/GeoGebraProfiler.h"

@interface GeogebraCommonUtilDebugSilentProfiler : GeogebraCommonUtilDebugGeoGebraProfiler

#pragma mark Public

- (instancetype)init;

- (void)profile;

- (void)profileEnd;

- (void)timeWithNSString:(NSString *)label;

- (void)timeEndWithNSString:(NSString *)label;

- (void)trace;

@end

J2OBJC_EMPTY_STATIC_INIT(GeogebraCommonUtilDebugSilentProfiler)

FOUNDATION_EXPORT void GeogebraCommonUtilDebugSilentProfiler_init(GeogebraCommonUtilDebugSilentProfiler *self);

FOUNDATION_EXPORT GeogebraCommonUtilDebugSilentProfiler *new_GeogebraCommonUtilDebugSilentProfiler_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(GeogebraCommonUtilDebugSilentProfiler)

#endif // _GeogebraCommonUtilDebugSilentProfiler_H_
