//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/kernel/geos/GeoCanvasImage.java
//

#ifndef _GeogebraCommonKernelGeosGeoCanvasImage_H_
#define _GeogebraCommonKernelGeosGeoCanvasImage_H_

#include "J2ObjC_header.h"
#include "geogebra/common/kernel/geos/GeoImage.h"

@class GeogebraCommonKernelConstruction;
@class GeogebraCommonKernelGeosGeoElement;
@class GeogebraCommonPluginGeoClassEnum;
@class JavaLangStringBuilder;
@protocol GeogebraCommonAwtGGraphics2D;
@protocol GeogebraCommonAwtMyImage;

@interface GeogebraCommonKernelGeosGeoCanvasImage : GeogebraCommonKernelGeosGeoImage

#pragma mark Public

- (instancetype)initWithGeogebraCommonKernelConstruction:(GeogebraCommonKernelConstruction *)c;

- (instancetype)initWithGeogebraCommonKernelConstruction:(GeogebraCommonKernelConstruction *)c
                                                 withInt:(jint)width
                                                 withInt:(jint)height;

- (instancetype)initWithGeogebraCommonKernelConstruction:(GeogebraCommonKernelConstruction *)c
                                            withNSString:(NSString *)label;

- (instancetype)initWithGeogebraCommonKernelGeosGeoCanvasImage:(GeogebraCommonKernelGeosGeoCanvasImage *)img;

- (GeogebraCommonKernelGeosGeoElement *)copy__ OBJC_METHOD_FAMILY_NONE;

- (id<GeogebraCommonAwtMyImage>)getFillImage;

- (GeogebraCommonPluginGeoClassEnum *)getGeoClassType;

- (id<GeogebraCommonAwtGGraphics2D>)getGraphics;

- (jint)getHeight;

- (jint)getWidth;

- (void)getXMLWithBoolean:(jboolean)getListenersToo
withJavaLangStringBuilder:(JavaLangStringBuilder *)sb;

- (jboolean)isGeoImage;

- (jboolean)isIndependent;

#pragma mark Protected

- (jboolean)showInEuclidianView;

@end

J2OBJC_EMPTY_STATIC_INIT(GeogebraCommonKernelGeosGeoCanvasImage)

FOUNDATION_EXPORT void GeogebraCommonKernelGeosGeoCanvasImage_initWithGeogebraCommonKernelConstruction_(GeogebraCommonKernelGeosGeoCanvasImage *self, GeogebraCommonKernelConstruction *c);

FOUNDATION_EXPORT GeogebraCommonKernelGeosGeoCanvasImage *new_GeogebraCommonKernelGeosGeoCanvasImage_initWithGeogebraCommonKernelConstruction_(GeogebraCommonKernelConstruction *c) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void GeogebraCommonKernelGeosGeoCanvasImage_initWithGeogebraCommonKernelConstruction_withNSString_(GeogebraCommonKernelGeosGeoCanvasImage *self, GeogebraCommonKernelConstruction *c, NSString *label);

FOUNDATION_EXPORT GeogebraCommonKernelGeosGeoCanvasImage *new_GeogebraCommonKernelGeosGeoCanvasImage_initWithGeogebraCommonKernelConstruction_withNSString_(GeogebraCommonKernelConstruction *c, NSString *label) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void GeogebraCommonKernelGeosGeoCanvasImage_initWithGeogebraCommonKernelConstruction_withInt_withInt_(GeogebraCommonKernelGeosGeoCanvasImage *self, GeogebraCommonKernelConstruction *c, jint width, jint height);

FOUNDATION_EXPORT GeogebraCommonKernelGeosGeoCanvasImage *new_GeogebraCommonKernelGeosGeoCanvasImage_initWithGeogebraCommonKernelConstruction_withInt_withInt_(GeogebraCommonKernelConstruction *c, jint width, jint height) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void GeogebraCommonKernelGeosGeoCanvasImage_initWithGeogebraCommonKernelGeosGeoCanvasImage_(GeogebraCommonKernelGeosGeoCanvasImage *self, GeogebraCommonKernelGeosGeoCanvasImage *img);

FOUNDATION_EXPORT GeogebraCommonKernelGeosGeoCanvasImage *new_GeogebraCommonKernelGeosGeoCanvasImage_initWithGeogebraCommonKernelGeosGeoCanvasImage_(GeogebraCommonKernelGeosGeoCanvasImage *img) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(GeogebraCommonKernelGeosGeoCanvasImage)

#endif // _GeogebraCommonKernelGeosGeoCanvasImage_H_
