//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeogebraiOS/GeogebraiOS/sources/org/geogebra/common/kernel/barycentric/CmdTriangleCurve.java
//

#ifndef _OrgGeogebraCommonKernelBarycentricCmdTriangleCurve_H_
#define _OrgGeogebraCommonKernelBarycentricCmdTriangleCurve_H_

#include "J2ObjC_header.h"
#include "org/geogebra/common/kernel/commands/CommandProcessor.h"

@class IOSObjectArray;
@class OrgGeogebraCommonKernelArithmeticCommand;
@class OrgGeogebraCommonKernelKernel;

@interface OrgGeogebraCommonKernelBarycentricCmdTriangleCurve : OrgGeogebraCommonKernelCommandsCommandProcessor

#pragma mark Public

- (instancetype)initWithOrgGeogebraCommonKernelKernel:(OrgGeogebraCommonKernelKernel *)kernel;

- (IOSObjectArray *)processWithOrgGeogebraCommonKernelArithmeticCommand:(OrgGeogebraCommonKernelArithmeticCommand *)c;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgGeogebraCommonKernelBarycentricCmdTriangleCurve)

FOUNDATION_EXPORT void OrgGeogebraCommonKernelBarycentricCmdTriangleCurve_initWithOrgGeogebraCommonKernelKernel_(OrgGeogebraCommonKernelBarycentricCmdTriangleCurve *self, OrgGeogebraCommonKernelKernel *kernel);

FOUNDATION_EXPORT OrgGeogebraCommonKernelBarycentricCmdTriangleCurve *new_OrgGeogebraCommonKernelBarycentricCmdTriangleCurve_initWithOrgGeogebraCommonKernelKernel_(OrgGeogebraCommonKernelKernel *kernel) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgGeogebraCommonKernelBarycentricCmdTriangleCurve)

#endif // _OrgGeogebraCommonKernelBarycentricCmdTriangleCurve_H_
