//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/kernel/algos/AlgoExtremumPolynomialInterval.java
//

#ifndef _GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval_H_
#define _GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval_H_

#include "J2ObjC_header.h"
#include "geogebra/common/kernel/algos/AlgoExtremumPolynomial.h"

@class GeogebraCommonKernelConstruction;
@class GeogebraCommonKernelGeosGeoFunction;
@class IOSObjectArray;

@interface GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval : GeogebraCommonKernelAlgosAlgoExtremumPolynomial

#pragma mark Public

- (instancetype)initWithGeogebraCommonKernelConstruction:(GeogebraCommonKernelConstruction *)cons
                                       withNSStringArray:(IOSObjectArray *)labels
                 withGeogebraCommonKernelGeosGeoFunction:(GeogebraCommonKernelGeosGeoFunction *)f;

- (void)compute;

@end

J2OBJC_EMPTY_STATIC_INIT(GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval)

FOUNDATION_EXPORT void GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval_initWithGeogebraCommonKernelConstruction_withNSStringArray_withGeogebraCommonKernelGeosGeoFunction_(GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval *self, GeogebraCommonKernelConstruction *cons, IOSObjectArray *labels, GeogebraCommonKernelGeosGeoFunction *f);

FOUNDATION_EXPORT GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval *new_GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval_initWithGeogebraCommonKernelConstruction_withNSStringArray_withGeogebraCommonKernelGeosGeoFunction_(GeogebraCommonKernelConstruction *cons, IOSObjectArray *labels, GeogebraCommonKernelGeosGeoFunction *f) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval)

#endif // _GeogebraCommonKernelAlgosAlgoExtremumPolynomialInterval_H_
