//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/geogebra3D/kernel3D/Kernel3D.java
//

#ifndef _GeogebraCommonGeogebra3DKernel3DKernel3D_H_
#define _GeogebraCommonGeogebra3DKernel3DKernel3D_H_

#include "J2ObjC_header.h"
#include "geogebra/common/kernel/Kernel.h"

@class GeogebraCommonGeogebra3DKernel3DGeosGeoAxis3D;
@class GeogebraCommonGeogebra3DKernel3DGeosGeoClippingCube3D;
@class GeogebraCommonGeogebra3DKernel3DGeosGeoPlane3D;
@class GeogebraCommonGeogebra3DKernel3DGeosGeoPlane3DConstant;
@class GeogebraCommonGeogebra3DKernel3DGeosGeoSpace;
@class GeogebraCommonIoMyXMLHandler;
@class GeogebraCommonKernelAlgosAlgoDispatcher;
@class GeogebraCommonKernelArithmeticExpressionNodeEvaluator;
@class GeogebraCommonKernelCommandsAlgebraProcessor;
@class GeogebraCommonKernelConstruction;
@class GeogebraCommonKernelGeosGeoElement;
@class GeogebraCommonKernelKernelNDGeoConicND;
@class GeogebraCommonMainApp;
@class IOSObjectArray;
@class JavaLangStringBuilder;
@class JavaUtilLinkedHashMap;
@class JavaUtilTreeSet;
@protocol GeogebraCommonKernelKernelNDGeoAxisND;
@protocol GeogebraCommonKernelKernelNDGeoDirectionND;
@protocol GeogebraCommonKernelKernelNDGeoLineND;
@protocol GeogebraCommonKernelKernelNDGeoPointND;
@protocol GeogebraCommonKernelKernelNDGeoRayND;
@protocol GeogebraCommonKernelKernelNDGeoSegmentND;
@protocol GeogebraCommonKernelManager3DInterface;

@interface GeogebraCommonGeogebra3DKernel3DKernel3D : GeogebraCommonKernelKernel

#pragma mark Public

- (instancetype)initWithGeogebraCommonMainApp:(GeogebraCommonMainApp *)app;

- (GeogebraCommonKernelGeosGeoElement *)copy3DWithGeogebraCommonKernelGeosGeoElement:(GeogebraCommonKernelGeosGeoElement *)geo OBJC_METHOD_FAMILY_NONE;

- (GeogebraCommonKernelGeosGeoElement *)copyInternal3DWithGeogebraCommonKernelConstruction:(GeogebraCommonKernelConstruction *)cons
                                                    withGeogebraCommonKernelGeosGeoElement:(GeogebraCommonKernelGeosGeoElement *)geo OBJC_METHOD_FAMILY_NONE;

- (GeogebraCommonKernelGeosGeoElement *)createGeoElementWithGeogebraCommonKernelConstruction:(GeogebraCommonKernelConstruction *)cons1
                                                                                withNSString:(NSString *)type;

- (GeogebraCommonGeogebra3DKernel3DGeosGeoClippingCube3D *)getClippingCube;

- (GeogebraCommonGeogebra3DKernel3DGeosGeoPlane3D *)getDefaultPlane;

- (NSString *)getModeTextWithInt:(jint)mode;

- (JavaUtilTreeSet *)getPointSet;

- (GeogebraCommonGeogebra3DKernel3DGeosGeoSpace *)getSpace;

- (id<GeogebraCommonKernelKernelNDGeoAxisND>)getXAxis3D;

- (NSString *)getXMLFileFormat;

- (GeogebraCommonGeogebra3DKernel3DGeosGeoPlane3DConstant *)getXOYPlane;

- (id<GeogebraCommonKernelKernelNDGeoAxisND>)getYAxis3D;

- (GeogebraCommonGeogebra3DKernel3DGeosGeoAxis3D *)getZAxis3D;

- (jdouble)getZmaxWithInt:(jint)i;

- (jdouble)getZminWithInt:(jint)i;

- (jdouble)getZscaleWithInt:(jint)i;

- (jboolean)handleCoordsWithGeogebraCommonKernelGeosGeoElement:(GeogebraCommonKernelGeosGeoElement *)geo
                                     withJavaUtilLinkedHashMap:(JavaUtilLinkedHashMap *)attrs;

- (jboolean)isZvarAllowed;

- (GeogebraCommonKernelCommandsAlgebraProcessor *)newAlgebraProcessorWithGeogebraCommonKernelKernel:(GeogebraCommonKernelKernel *)kernel OBJC_METHOD_FAMILY_NONE;

- (GeogebraCommonKernelArithmeticExpressionNodeEvaluator *)newExpressionNodeEvaluatorWithGeogebraCommonKernelKernel:(GeogebraCommonKernelKernel *)kernel OBJC_METHOD_FAMILY_NONE;

- (id<GeogebraCommonKernelManager3DInterface>)newManager3DWithGeogebraCommonKernelKernel:(GeogebraCommonKernelKernel *)kernel OBJC_METHOD_FAMILY_NONE;

- (GeogebraCommonIoMyXMLHandler *)newMyXMLHandlerWithGeogebraCommonKernelKernel:(GeogebraCommonKernelKernel *)kernel
                                           withGeogebraCommonKernelConstruction:(GeogebraCommonKernelConstruction *)construction OBJC_METHOD_FAMILY_NONE;

- (id<GeogebraCommonKernelKernelNDGeoLineND>)OrthogonalLineWithNSString:(NSString *)label
                             withGeogebraCommonKernelKernelNDGeoPointND:(id<GeogebraCommonKernelKernelNDGeoPointND>)P
                              withGeogebraCommonKernelKernelNDGeoLineND:(id<GeogebraCommonKernelKernelNDGeoLineND>)l
                         withGeogebraCommonKernelKernelNDGeoDirectionND:(id<GeogebraCommonKernelKernelNDGeoDirectionND>)direction;

- (IOSObjectArray *)PolygonNDWithNSStringArray:(IOSObjectArray *)labels
withGeogebraCommonKernelKernelNDGeoPointNDArray:(IOSObjectArray *)P;

- (IOSObjectArray *)PolyLineNDWithNSStringArray:(IOSObjectArray *)labels
withGeogebraCommonKernelKernelNDGeoPointNDArray:(IOSObjectArray *)P;

- (id<GeogebraCommonKernelKernelNDGeoRayND>)RayNDWithNSString:(NSString *)label
                   withGeogebraCommonKernelKernelNDGeoPointND:(id<GeogebraCommonKernelKernelNDGeoPointND>)P
                   withGeogebraCommonKernelKernelNDGeoPointND:(id<GeogebraCommonKernelKernelNDGeoPointND>)Q;

- (id<GeogebraCommonKernelKernelNDGeoSegmentND>)SegmentNDWithNSString:(NSString *)label
                           withGeogebraCommonKernelKernelNDGeoPointND:(id<GeogebraCommonKernelKernelNDGeoPointND>)P
                           withGeogebraCommonKernelKernelNDGeoPointND:(id<GeogebraCommonKernelKernelNDGeoPointND>)Q;

- (void)setEuclidianView3DBoundsWithInt:(jint)view
                             withDouble:(jdouble)xmin
                             withDouble:(jdouble)xmax
                             withDouble:(jdouble)ymin
                             withDouble:(jdouble)ymax
                             withDouble:(jdouble)zmin
                             withDouble:(jdouble)zmax
                             withDouble:(jdouble)xscale
                             withDouble:(jdouble)yscale
                             withDouble:(jdouble)zscale;

- (GeogebraCommonKernelGeosGeoElement *)wrapInVectorWithGeogebraCommonKernelKernelNDGeoPointND:(id<GeogebraCommonKernelKernelNDGeoPointND>)pt;

#pragma mark Protected

- (GeogebraCommonKernelAlgosAlgoDispatcher *)newAlgoDispatcherWithGeogebraCommonKernelConstruction:(GeogebraCommonKernelConstruction *)cons1 OBJC_METHOD_FAMILY_NONE;

- (void)newConstruction OBJC_METHOD_FAMILY_NONE;

- (void)RigidPolygonAddEndOfCommandWithJavaLangStringBuilder:(JavaLangStringBuilder *)sb
                                                 withBoolean:(jboolean)is3D;

- (id<GeogebraCommonKernelKernelNDGeoPointND>)RigidPolygonPointOnCircleWithGeogebraCommonKernelKernelNDGeoConicND:(GeogebraCommonKernelKernelNDGeoConicND *)circle
                                                                       withGeogebraCommonKernelKernelNDGeoPointND:(id<GeogebraCommonKernelKernelNDGeoPointND>)point1;

@end

J2OBJC_EMPTY_STATIC_INIT(GeogebraCommonGeogebra3DKernel3DKernel3D)

FOUNDATION_EXPORT void GeogebraCommonGeogebra3DKernel3DKernel3D_initWithGeogebraCommonMainApp_(GeogebraCommonGeogebra3DKernel3DKernel3D *self, GeogebraCommonMainApp *app);

FOUNDATION_EXPORT GeogebraCommonGeogebra3DKernel3DKernel3D *new_GeogebraCommonGeogebra3DKernel3DKernel3D_initWithGeogebraCommonMainApp_(GeogebraCommonMainApp *app) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(GeogebraCommonGeogebra3DKernel3DKernel3D)

#endif // _GeogebraCommonGeogebra3DKernel3DKernel3D_H_
