//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/geogebra3D/euclidian3D/draw/DrawLabel3D.java
//

#ifndef _GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D_H_
#define _GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D_H_

#include "J2ObjC_header.h"

@class GeogebraCommonAwtGColor;
@class GeogebraCommonAwtGFont;
@class GeogebraCommonAwtGPoint;
@class GeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D;
@class GeogebraCommonGeogebra3DEuclidian3DEuclidianView3D;
@class GeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer;
@class GeogebraCommonKernelMatrixCoords;
@protocol GeogebraCommonAwtGBufferedImage;
@protocol GeogebraCommonAwtGGraphics2D;
@protocol GeogebraCommonAwtGRectangle;

@interface GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D : NSObject {
 @public
  NSString *text_;
  GeogebraCommonAwtGFont *font_;
  GeogebraCommonKernelMatrixCoords *origin_;
  jint height_, width_;
  GeogebraCommonGeogebra3DEuclidian3DEuclidianView3D *view_;
  id<GeogebraCommonAwtGGraphics2D> tempGraphics_;
  jboolean hasIndex_;
  jint drawX_, drawY_, drawZ_;
  jint backgroundIndex_;
}

#pragma mark Public

- (instancetype)initWithGeogebraCommonGeogebra3DEuclidian3DEuclidianView3D:(GeogebraCommonGeogebra3DEuclidian3DEuclidianView3D *)view
                     withGeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D:(GeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D *)drawable;

- (void)drawWithGeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer:(GeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer *)renderer;

- (void)drawWithGeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer:(GeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer *)renderer
                                                      withBoolean:(jboolean)forPicking;

- (jint)getDrawZ;

- (jint)getHeight;

- (jint)getHeightPowerOfTwo;

- (jint)getTextureIndex;

- (jint)getWidth;

- (jint)getWidthPowerOfTwo;

- (jboolean)hitWithGeogebraCommonAwtGPoint:(GeogebraCommonAwtGPoint *)pos;

- (jboolean)isPickable;

- (void)setAnchorWithBoolean:(jboolean)flag;

- (void)setDimensionPowerOfTwoWithInt:(jint)w
                              withInt:(jint)h;

- (void)setIsVisibleWithBoolean:(jboolean)flag;

- (void)setPickingDimensionWithInt:(jint)x
                           withInt:(jint)y
                           withInt:(jint)w
                           withInt:(jint)h;

- (void)setTextureIndexWithInt:(jint)i;

- (void)setWaitForReset;

- (void)updateWithNSString:(NSString *)text
withGeogebraCommonAwtGFont:(GeogebraCommonAwtGFont *)font
withGeogebraCommonAwtGColor:(GeogebraCommonAwtGColor *)color
withGeogebraCommonKernelMatrixCoords:(GeogebraCommonKernelMatrixCoords *)v
                 withFloat:(jfloat)xOffset
                 withFloat:(jfloat)yOffset;

- (void)updateWithNSString:(NSString *)text
withGeogebraCommonAwtGFont:(GeogebraCommonAwtGFont *)font
withGeogebraCommonAwtGColor:(GeogebraCommonAwtGColor *)backgroundColor
withGeogebraCommonAwtGColor:(GeogebraCommonAwtGColor *)color
withGeogebraCommonKernelMatrixCoords:(GeogebraCommonKernelMatrixCoords *)v
                 withFloat:(jfloat)xOffset
                 withFloat:(jfloat)yOffset;

- (void)updateDrawPosition;

- (void)updatePositionWithGeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer:(GeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer *)renderer;

- (jboolean)waitForReset;

#pragma mark Protected

- (id<GeogebraCommonAwtGBufferedImage>)createBufferedImage;

- (id<GeogebraCommonAwtGGraphics2D>)createGraphics2DWithGeogebraCommonAwtGBufferedImage:(id<GeogebraCommonAwtGBufferedImage>)bimg;

- (id<GeogebraCommonAwtGBufferedImage>)draw;

- (void)drawWithGeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer:(GeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer *)renderer
                                                          withInt:(jint)x
                                                          withInt:(jint)y
                                                          withInt:(jint)z;

- (id<GeogebraCommonAwtGRectangle>)getBounds;

@end

J2OBJC_EMPTY_STATIC_INIT(GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D)

J2OBJC_FIELD_SETTER(GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D, text_, NSString *)
J2OBJC_FIELD_SETTER(GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D, font_, GeogebraCommonAwtGFont *)
J2OBJC_FIELD_SETTER(GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D, origin_, GeogebraCommonKernelMatrixCoords *)
J2OBJC_FIELD_SETTER(GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D, view_, GeogebraCommonGeogebra3DEuclidian3DEuclidianView3D *)
J2OBJC_FIELD_SETTER(GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D, tempGraphics_, id<GeogebraCommonAwtGGraphics2D>)

FOUNDATION_EXPORT void GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D_initWithGeogebraCommonGeogebra3DEuclidian3DEuclidianView3D_withGeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D_(GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D *self, GeogebraCommonGeogebra3DEuclidian3DEuclidianView3D *view, GeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D *drawable);

FOUNDATION_EXPORT GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D *new_GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D_initWithGeogebraCommonGeogebra3DEuclidian3DEuclidianView3D_withGeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D_(GeogebraCommonGeogebra3DEuclidian3DEuclidianView3D *view, GeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D *drawable) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D)

#endif // _GeogebraCommonGeogebra3DEuclidian3DDrawDrawLabel3D_H_
