//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/edu/uci/ics/jung/algorithms/scoring/DistanceCentralityScorer.java
//


#include "J2ObjC_source.h"
#include "edu/uci/ics/jung/algorithms/scoring/DistanceCentralityScorer.h"
#include "edu/uci/ics/jung/algorithms/shortestpath/DijkstraDistance.h"
#include "edu/uci/ics/jung/algorithms/shortestpath/Distance.h"
#include "edu/uci/ics/jung/algorithms/shortestpath/UnweightedShortestPath.h"
#include "edu/uci/ics/jung/graph/Hypergraph.h"
#include "java/lang/Double.h"
#include "java/util/Collection.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"
#include "org/apache/commons/collections15/Transformer.h"

@implementation EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer

- (instancetype)initWithEduUciIcsJungGraphHypergraph:(id<EduUciIcsJungGraphHypergraph>)graph
     withEduUciIcsJungAlgorithmsShortestpathDistance:(id<EduUciIcsJungAlgorithmsShortestpathDistance>)distance
                                         withBoolean:(jboolean)averaging
                                         withBoolean:(jboolean)ignore_missing
                                         withBoolean:(jboolean)ignore_self_distances {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_withBoolean_withBoolean_(self, graph, distance, averaging, ignore_missing, ignore_self_distances);
  return self;
}

- (instancetype)initWithEduUciIcsJungGraphHypergraph:(id<EduUciIcsJungGraphHypergraph>)graph
     withEduUciIcsJungAlgorithmsShortestpathDistance:(id<EduUciIcsJungAlgorithmsShortestpathDistance>)distance
                                         withBoolean:(jboolean)averaging {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_(self, graph, distance, averaging);
  return self;
}

- (instancetype)initWithEduUciIcsJungGraphHypergraph:(id<EduUciIcsJungGraphHypergraph>)graph
        withOrgApacheCommonsCollections15Transformer:(id<OrgApacheCommonsCollections15Transformer>)edge_weights
                                         withBoolean:(jboolean)averaging
                                         withBoolean:(jboolean)ignore_missing
                                         withBoolean:(jboolean)ignore_self_distances {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_withBoolean_withBoolean_withBoolean_(self, graph, edge_weights, averaging, ignore_missing, ignore_self_distances);
  return self;
}

- (instancetype)initWithEduUciIcsJungGraphHypergraph:(id<EduUciIcsJungGraphHypergraph>)graph
        withOrgApacheCommonsCollections15Transformer:(id<OrgApacheCommonsCollections15Transformer>)edge_weights
                                         withBoolean:(jboolean)averaging {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_withBoolean_(self, graph, edge_weights, averaging);
  return self;
}

- (instancetype)initWithEduUciIcsJungGraphHypergraph:(id<EduUciIcsJungGraphHypergraph>)graph
                                         withBoolean:(jboolean)averaging
                                         withBoolean:(jboolean)ignore_missing
                                         withBoolean:(jboolean)ignore_self_distances {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withBoolean_withBoolean_withBoolean_(self, graph, averaging, ignore_missing, ignore_self_distances);
  return self;
}

- (instancetype)initWithEduUciIcsJungGraphHypergraph:(id<EduUciIcsJungGraphHypergraph>)graph
                                         withBoolean:(jboolean)averaging {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withBoolean_(self, graph, averaging);
  return self;
}

- (JavaLangDouble *)getVertexScoreWithId:(id)v {
  JavaLangDouble *value = [((id<JavaUtilMap>) nil_chk(output_)) getWithId:v];
  if (value != nil) {
    if ([value doubleValue] < 0) return nil;
    return value;
  }
  id<JavaUtilMap> v_distances = [new_JavaUtilHashMap_initWithJavaUtilMap_([((id<EduUciIcsJungAlgorithmsShortestpathDistance>) nil_chk(distance_)) getDistanceMapWithId:v]) autorelease];
  if (ignore_self_distances_) [v_distances removeWithId:v];
  if (!ignore_missing_) {
    jint num_dests = [((id<EduUciIcsJungGraphHypergraph>) nil_chk(graph_)) getVertexCount] - (ignore_self_distances_ ? 1 : 0);
    if ([v_distances size] != num_dests) {
      [output_ putWithId:v withId:JavaLangDouble_valueOfWithDouble_(-1.0)];
      return nil;
    }
  }
  JavaLangDouble *sum = JavaLangDouble_valueOfWithDouble_(0.0);
  for (id __strong w in nil_chk([((id<EduUciIcsJungGraphHypergraph>) nil_chk(graph_)) getVertices])) {
    if ([nil_chk(w) isEqual:v] && ignore_self_distances_) continue;
    NSNumber *w_distance = [v_distances getWithId:w];
    if (w_distance == nil) if (ignore_missing_) continue;
    else {
      [output_ putWithId:v withId:JavaLangDouble_valueOfWithDouble_(-1.0)];
      return nil;
    }
    else sum = JavaLangDouble_valueOfWithDouble_([sum doubleValue] + [w_distance doubleValue]);
  }
  value = sum;
  if (averaging_) value = JavaLangDouble_valueOfWithDouble_([value doubleValue] / [v_distances size]);
  jdouble score = [value doubleValue] == 0 ? JavaLangDouble_POSITIVE_INFINITY : 1.0 / [value doubleValue];
  [output_ putWithId:v withId:JavaLangDouble_valueOfWithDouble_(score)];
  return JavaLangDouble_valueOfWithDouble_(score);
}

- (void)dealloc {
  RELEASE_(graph_);
  RELEASE_(distance_);
  RELEASE_(output_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithEduUciIcsJungGraphHypergraph:withEduUciIcsJungAlgorithmsShortestpathDistance:withBoolean:withBoolean:withBoolean:", "DistanceCentralityScorer", NULL, 0x1, NULL, NULL },
    { "initWithEduUciIcsJungGraphHypergraph:withEduUciIcsJungAlgorithmsShortestpathDistance:withBoolean:", "DistanceCentralityScorer", NULL, 0x1, NULL, NULL },
    { "initWithEduUciIcsJungGraphHypergraph:withOrgApacheCommonsCollections15Transformer:withBoolean:withBoolean:withBoolean:", "DistanceCentralityScorer", NULL, 0x1, NULL, NULL },
    { "initWithEduUciIcsJungGraphHypergraph:withOrgApacheCommonsCollections15Transformer:withBoolean:", "DistanceCentralityScorer", NULL, 0x1, NULL, NULL },
    { "initWithEduUciIcsJungGraphHypergraph:withBoolean:withBoolean:withBoolean:", "DistanceCentralityScorer", NULL, 0x1, NULL, NULL },
    { "initWithEduUciIcsJungGraphHypergraph:withBoolean:", "DistanceCentralityScorer", NULL, 0x1, NULL, NULL },
    { "getVertexScoreWithId:", "getVertexScore", "Ljava.lang.Double;", 0x1, NULL, "(TV;)Ljava/lang/Double;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "graph_", NULL, 0x4, "Ledu.uci.ics.jung.graph.Hypergraph;", NULL, "Ledu/uci/ics/jung/graph/Hypergraph<TV;TE;>;",  },
    { "distance_", NULL, 0x4, "Ledu.uci.ics.jung.algorithms.shortestpath.Distance;", NULL, "Ledu/uci/ics/jung/algorithms/shortestpath/Distance<TV;>;",  },
    { "output_", NULL, 0x4, "Ljava.util.Map;", NULL, "Ljava/util/Map<TV;Ljava/lang/Double;>;",  },
    { "averaging_", NULL, 0x4, "Z", NULL, NULL,  },
    { "ignore_missing_", NULL, 0x4, "Z", NULL, NULL,  },
    { "ignore_self_distances_", NULL, 0x4, "Z", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer = { 2, "DistanceCentralityScorer", "edu.uci.ics.jung.algorithms.scoring", NULL, 0x1, 7, methods, 6, fields, 0, NULL, 0, NULL, NULL, "<V:Ljava/lang/Object;E:Ljava/lang/Object;>Ljava/lang/Object;Ledu/uci/ics/jung/algorithms/scoring/VertexScorer<TV;Ljava/lang/Double;>;" };
  return &_EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer;
}

@end

void EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_withBoolean_withBoolean_(EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self, id<EduUciIcsJungGraphHypergraph> graph, id<EduUciIcsJungAlgorithmsShortestpathDistance> distance, jboolean averaging, jboolean ignore_missing, jboolean ignore_self_distances) {
  NSObject_init(self);
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_set_graph_(self, graph);
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_set_distance_(self, distance);
  self->averaging_ = averaging;
  self->ignore_missing_ = ignore_missing;
  self->ignore_self_distances_ = ignore_self_distances;
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_setAndConsume_output_(self, new_JavaUtilHashMap_init());
}

EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *new_EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_withBoolean_withBoolean_(id<EduUciIcsJungGraphHypergraph> graph, id<EduUciIcsJungAlgorithmsShortestpathDistance> distance, jboolean averaging, jboolean ignore_missing, jboolean ignore_self_distances) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self = [EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer alloc];
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_withBoolean_withBoolean_(self, graph, distance, averaging, ignore_missing, ignore_self_distances);
  return self;
}

void EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_(EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self, id<EduUciIcsJungGraphHypergraph> graph, id<EduUciIcsJungAlgorithmsShortestpathDistance> distance, jboolean averaging) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_withBoolean_withBoolean_(self, graph, distance, averaging, YES, YES);
}

EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *new_EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_(id<EduUciIcsJungGraphHypergraph> graph, id<EduUciIcsJungAlgorithmsShortestpathDistance> distance, jboolean averaging) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self = [EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer alloc];
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_(self, graph, distance, averaging);
  return self;
}

void EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_withBoolean_withBoolean_withBoolean_(EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self, id<EduUciIcsJungGraphHypergraph> graph, id<OrgApacheCommonsCollections15Transformer> edge_weights, jboolean averaging, jboolean ignore_missing, jboolean ignore_self_distances) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_withBoolean_withBoolean_(self, graph, [new_EduUciIcsJungAlgorithmsShortestpathDijkstraDistance_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_(graph, edge_weights) autorelease], averaging, ignore_missing, ignore_self_distances);
}

EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *new_EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_withBoolean_withBoolean_withBoolean_(id<EduUciIcsJungGraphHypergraph> graph, id<OrgApacheCommonsCollections15Transformer> edge_weights, jboolean averaging, jboolean ignore_missing, jboolean ignore_self_distances) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self = [EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer alloc];
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_withBoolean_withBoolean_withBoolean_(self, graph, edge_weights, averaging, ignore_missing, ignore_self_distances);
  return self;
}

void EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_withBoolean_(EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self, id<EduUciIcsJungGraphHypergraph> graph, id<OrgApacheCommonsCollections15Transformer> edge_weights, jboolean averaging) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_withBoolean_withBoolean_(self, graph, [new_EduUciIcsJungAlgorithmsShortestpathDijkstraDistance_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_(graph, edge_weights) autorelease], averaging, YES, YES);
}

EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *new_EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_withBoolean_(id<EduUciIcsJungGraphHypergraph> graph, id<OrgApacheCommonsCollections15Transformer> edge_weights, jboolean averaging) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self = [EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer alloc];
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withOrgApacheCommonsCollections15Transformer_withBoolean_(self, graph, edge_weights, averaging);
  return self;
}

void EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withBoolean_withBoolean_withBoolean_(EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self, id<EduUciIcsJungGraphHypergraph> graph, jboolean averaging, jboolean ignore_missing, jboolean ignore_self_distances) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_withBoolean_withBoolean_(self, graph, [new_EduUciIcsJungAlgorithmsShortestpathUnweightedShortestPath_initWithEduUciIcsJungGraphHypergraph_(graph) autorelease], averaging, ignore_missing, ignore_self_distances);
}

EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *new_EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withBoolean_withBoolean_withBoolean_(id<EduUciIcsJungGraphHypergraph> graph, jboolean averaging, jboolean ignore_missing, jboolean ignore_self_distances) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self = [EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer alloc];
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withBoolean_withBoolean_withBoolean_(self, graph, averaging, ignore_missing, ignore_self_distances);
  return self;
}

void EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withBoolean_(EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self, id<EduUciIcsJungGraphHypergraph> graph, jboolean averaging) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withEduUciIcsJungAlgorithmsShortestpathDistance_withBoolean_withBoolean_withBoolean_(self, graph, [new_EduUciIcsJungAlgorithmsShortestpathUnweightedShortestPath_initWithEduUciIcsJungGraphHypergraph_(graph) autorelease], averaging, YES, YES);
}

EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *new_EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withBoolean_(id<EduUciIcsJungGraphHypergraph> graph, jboolean averaging) {
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer *self = [EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer alloc];
  EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer_initWithEduUciIcsJungGraphHypergraph_withBoolean_(self, graph, averaging);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EduUciIcsJungAlgorithmsScoringDistanceCentralityScorer)
