//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/gui/dialog/ToolInputOutputListener.java
//


#include "J2ObjC_source.h"
#include "geogebra/common/gui/dialog/ToolInputOutputListener.h"

@interface GeogebraCommonGuiDialogToolInputOutputListener : NSObject
@end

@implementation GeogebraCommonGuiDialogToolInputOutputListener

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "updateLists", NULL, "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _GeogebraCommonGuiDialogToolInputOutputListener = { 2, "ToolInputOutputListener", "geogebra.common.gui.dialog", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_GeogebraCommonGuiDialogToolInputOutputListener;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GeogebraCommonGuiDialogToolInputOutputListener)
