//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/cas/view/MarbleRenderer.java
//


#include "J2ObjC_source.h"
#include "geogebra/common/cas/view/MarbleRenderer.h"

@interface GeogebraCommonCasViewMarbleRenderer : NSObject
@end

@implementation GeogebraCommonCasViewMarbleRenderer

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setMarbleValueWithBoolean:", "setMarbleValue", "V", 0x401, NULL, NULL },
    { "setMarbleVisibleWithBoolean:", "setMarbleVisible", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _GeogebraCommonCasViewMarbleRenderer = { 2, "MarbleRenderer", "geogebra.common.cas.view", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_GeogebraCommonCasViewMarbleRenderer;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GeogebraCommonCasViewMarbleRenderer)
