//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/awt/GRenderedImage.java
//


#include "J2ObjC_source.h"
#include "geogebra/common/awt/GRenderedImage.h"

@interface GeogebraCommonAwtGRenderedImage : NSObject
@end

@implementation GeogebraCommonAwtGRenderedImage

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _GeogebraCommonAwtGRenderedImage = { 2, "GRenderedImage", "geogebra.common.awt", NULL, 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_GeogebraCommonAwtGRenderedImage;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GeogebraCommonAwtGRenderedImage)
