//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/kernel/locusequ/arith/EquationBinaryOperator.java
//


#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "geogebra/common/kernel/locusequ/arith/EquationBinaryOperator.h"
#include "geogebra/common/kernel/locusequ/arith/EquationExpression.h"
#include "geogebra/common/kernel/locusequ/arith/EquationOperator.h"

@implementation GeogebraCommonKernelLocusequArithEquationBinaryOperator

- (instancetype)initWithGeogebraCommonKernelLocusequArithEquationExpression:(GeogebraCommonKernelLocusequArithEquationExpression *)expr1
                    withGeogebraCommonKernelLocusequArithEquationExpression:(GeogebraCommonKernelLocusequArithEquationExpression *)expr2 {
  GeogebraCommonKernelLocusequArithEquationBinaryOperator_initWithGeogebraCommonKernelLocusequArithEquationExpression_withGeogebraCommonKernelLocusequArithEquationExpression_(self, expr1, expr2);
  return self;
}

- (GeogebraCommonKernelLocusequArithEquationExpression *)getFirstExpression {
  return IOSObjectArray_Get(nil_chk(self->exprs_), 0);
}

- (GeogebraCommonKernelLocusequArithEquationExpression *)getSecondExpression {
  return IOSObjectArray_Get(nil_chk(self->exprs_), 1);
}

- (jdouble)operationWithDouble:(jdouble)a
                    withDouble:(jdouble)b {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (jdouble)computeValueImpl {
  return [self operationWithDouble:[((GeogebraCommonKernelLocusequArithEquationExpression *) nil_chk([self getFirstExpression])) computeValueImpl] withDouble:[((GeogebraCommonKernelLocusequArithEquationExpression *) nil_chk([self getSecondExpression])) computeValueImpl]];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithGeogebraCommonKernelLocusequArithEquationExpression:withGeogebraCommonKernelLocusequArithEquationExpression:", "EquationBinaryOperator", NULL, 0x1, NULL, NULL },
    { "getFirstExpression", NULL, "Lgeogebra.common.kernel.locusequ.arith.EquationExpression;", 0x1, NULL, NULL },
    { "getSecondExpression", NULL, "Lgeogebra.common.kernel.locusequ.arith.EquationExpression;", 0x1, NULL, NULL },
    { "operationWithDouble:withDouble:", "operation", "D", 0x404, NULL, NULL },
    { "computeValueImpl", NULL, "D", 0x4, NULL, NULL },
  };
  static const J2ObjcClassInfo _GeogebraCommonKernelLocusequArithEquationBinaryOperator = { 2, "EquationBinaryOperator", "geogebra.common.kernel.locusequ.arith", NULL, 0x401, 5, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_GeogebraCommonKernelLocusequArithEquationBinaryOperator;
}

@end

void GeogebraCommonKernelLocusequArithEquationBinaryOperator_initWithGeogebraCommonKernelLocusequArithEquationExpression_withGeogebraCommonKernelLocusequArithEquationExpression_(GeogebraCommonKernelLocusequArithEquationBinaryOperator *self, GeogebraCommonKernelLocusequArithEquationExpression *expr1, GeogebraCommonKernelLocusequArithEquationExpression *expr2) {
  GeogebraCommonKernelLocusequArithEquationOperator_initWithGeogebraCommonKernelLocusequArithEquationExpressionArray_(self, [IOSObjectArray arrayWithObjects:(id[]){ expr1, expr2 } count:2 type:GeogebraCommonKernelLocusequArithEquationExpression_class_()]);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(GeogebraCommonKernelLocusequArithEquationBinaryOperator)
