//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeogebraiOS/GeogebraiOS/sources/org/geogebra/common/kernel/discrete/signalprocessor/voronoi/VoronoiShared.java
//


#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Math.h"
#include "java/lang/RuntimeException.h"
#include "org/geogebra/common/kernel/discrete/signalprocessor/voronoi/VoronoiShared.h"
#include "org/geogebra/common/kernel/discrete/signalprocessor/voronoi/eventqueue/VCircleEvent.h"
#include "org/geogebra/common/kernel/discrete/signalprocessor/voronoi/eventqueue/VSiteEvent.h"

@implementation OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared

+ (IOSDoubleArray *)solveQuadraticWithDouble:(jdouble)a
                                  withDouble:(jdouble)b
                                  withDouble:(jdouble)c {
  return OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_solveQuadraticWithDouble_withDouble_withDouble_(a, b, c);
}

+ (OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVCircleEvent *)calculateCenterWithOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent:(OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent *)u
                                                                                                withOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent:(OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent *)v
                                                                                                withOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent:(OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent *)w {
  return OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_calculateCenterWithOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent_withOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent_withOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent_(u, v, w);
}

- (instancetype)init {
  OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "solveQuadraticWithDouble:withDouble:withDouble:", "solveQuadratic", "[D", 0x9, NULL, NULL },
    { "calculateCenterWithOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent:withOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent:withOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent:", "calculateCenter", "Lorg.geogebra.common.kernel.discrete.signalprocessor.voronoi.eventqueue.VCircleEvent;", 0x9, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared = { 2, "VoronoiShared", "org.geogebra.common.kernel.discrete.signalprocessor.voronoi", NULL, 0x1, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared;
}

@end

IOSDoubleArray *OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_solveQuadraticWithDouble_withDouble_withDouble_(jdouble a, jdouble b, jdouble c) {
  OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_initialize();
  if (a == 0.0) {
    if (b != 0.0) {
      IOSDoubleArray *answers = [IOSDoubleArray arrayWithLength:1];
      *IOSDoubleArray_GetRef(answers, 0) = -1 * c / b;
      return answers;
    }
    else {
      @throw [new_JavaLangRuntimeException_initWithNSString_(@"Only given a non-zero c value") autorelease];
    }
  }
  else {
    IOSDoubleArray *answers = [IOSDoubleArray arrayWithLength:2];
    jdouble bsqrdplus4ac = JavaLangMath_sqrtWithDouble_(b * b - 4.0 * a * c);
    *IOSDoubleArray_GetRef(answers, 0) = (-b + bsqrdplus4ac) / (2.0 * a);
    *IOSDoubleArray_GetRef(answers, 1) = (-b - bsqrdplus4ac) / (2.0 * a);
    return answers;
  }
}

OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVCircleEvent *OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_calculateCenterWithOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent_withOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent_withOrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent_(OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent *u, OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent *v, OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent *w) {
  OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_initialize();
  jdouble a = ([((OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent *) nil_chk(u)) getX] - [((OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent *) nil_chk(v)) getX]) * ([v getY] - [((OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVSiteEvent *) nil_chk(w)) getY]) - ([u getY] - [v getY]) * ([v getX] - [w getX]);
  if (a > 0) {
    jdouble b1 = ([u getX] - [v getX]) * ([u getX] + [v getX]) + ([u getY] - [v getY]) * ([u getY] + [v getY]);
    jdouble b2 = ([v getX] - [w getX]) * ([v getX] + [w getX]) + ([v getY] - [w getY]) * ([v getY] + [w getY]);
    OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVCircleEvent *centerpoint = [new_OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiEventqueueVCircleEvent_init() autorelease];
    jdouble x = (b1 * ([v getY] - [w getY]) - b2 * ([u getY] - [v getY])) / (2.0 * a);
    jdouble center_y = (b2 * ([u getX] - [v getX]) - b1 * ([v getX] - [w getX])) / (2.0 * a);
    [centerpoint setXWithInt:J2ObjCFpToInt(x)];
    [centerpoint setYWithInt:J2ObjCFpToInt((center_y + JavaLangMath_sqrtWithDouble_((x - [u getX]) * (x - [u getX]) + (center_y - [u getY]) * (center_y - [u getY]))))];
    [centerpoint setCenterYWithInt:J2ObjCFpToInt(center_y)];
    return centerpoint;
  }
  else {
    return nil;
  }
}

void OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_init(OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared *self) {
  NSObject_init(self);
}

OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared *new_OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_init() {
  OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared *self = [OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared alloc];
  OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgGeogebraCommonKernelDiscreteSignalprocessorVoronoiVoronoiShared)
