//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/apache/commons/math/ode/SecondOrderDifferentialEquations.java
//


#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "org/apache/commons/math/ode/DerivativeException.h"
#include "org/apache/commons/math/ode/SecondOrderDifferentialEquations.h"

@interface OrgApacheCommonsMathOdeSecondOrderDifferentialEquations : NSObject
@end

@implementation OrgApacheCommonsMathOdeSecondOrderDifferentialEquations

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getDimension", NULL, "I", 0x401, NULL, NULL },
    { "computeSecondDerivativesWithDouble:withDoubleArray:withDoubleArray:withDoubleArray:", "computeSecondDerivatives", "V", 0x401, "Lorg.apache.commons.math.ode.DerivativeException;", NULL },
  };
  static const J2ObjcClassInfo _OrgApacheCommonsMathOdeSecondOrderDifferentialEquations = { 2, "SecondOrderDifferentialEquations", "org.apache.commons.math.ode", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheCommonsMathOdeSecondOrderDifferentialEquations;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheCommonsMathOdeSecondOrderDifferentialEquations)
