//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/geogebra/common/util/debug/SilentProfiler.java
//


#include "J2ObjC_source.h"
#include "org/geogebra/common/util/debug/GeoGebraProfiler.h"
#include "org/geogebra/common/util/debug/SilentProfiler.h"

@implementation OrgGeogebraCommonUtilDebugSilentProfiler

- (void)profile {
}

- (void)profileEnd {
}

- (void)timeWithNSString:(NSString *)label {
}

- (void)timeEndWithNSString:(NSString *)label {
}

- (void)trace {
}

- (instancetype)init {
  OrgGeogebraCommonUtilDebugSilentProfiler_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "profile", NULL, "V", 0x1, NULL, NULL },
    { "profileEnd", NULL, "V", 0x1, NULL, NULL },
    { "timeWithNSString:", "time", "V", 0x1, NULL, NULL },
    { "timeEndWithNSString:", "timeEnd", "V", 0x1, NULL, NULL },
    { "trace", NULL, "V", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgGeogebraCommonUtilDebugSilentProfiler = { 2, "SilentProfiler", "org.geogebra.common.util.debug", NULL, 0x1, 6, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgGeogebraCommonUtilDebugSilentProfiler;
}

@end

void OrgGeogebraCommonUtilDebugSilentProfiler_init(OrgGeogebraCommonUtilDebugSilentProfiler *self) {
  (void) OrgGeogebraCommonUtilDebugGeoGebraProfiler_init(self);
}

OrgGeogebraCommonUtilDebugSilentProfiler *new_OrgGeogebraCommonUtilDebugSilentProfiler_init() {
  OrgGeogebraCommonUtilDebugSilentProfiler *self = [OrgGeogebraCommonUtilDebugSilentProfiler alloc];
  OrgGeogebraCommonUtilDebugSilentProfiler_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgGeogebraCommonUtilDebugSilentProfiler)
