//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/geogebra/common/factories/AwtFactory.java
//


#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "org/geogebra/common/awt/Component.h"
#include "org/geogebra/common/awt/GAffineTransform.h"
#include "org/geogebra/common/awt/GAlphaComposite.h"
#include "org/geogebra/common/awt/GArc2D.h"
#include "org/geogebra/common/awt/GArea.h"
#include "org/geogebra/common/awt/GBasicStroke.h"
#include "org/geogebra/common/awt/GBufferedImage.h"
#include "org/geogebra/common/awt/GColor.h"
#include "org/geogebra/common/awt/GCubicCurve2D.h"
#include "org/geogebra/common/awt/GDimension.h"
#include "org/geogebra/common/awt/GEllipse2DDouble.h"
#include "org/geogebra/common/awt/GEllipse2DFloat.h"
#include "org/geogebra/common/awt/GFont.h"
#include "org/geogebra/common/awt/GFontRenderContext.h"
#include "org/geogebra/common/awt/GGeneralPath.h"
#include "org/geogebra/common/awt/GGradientPaint.h"
#include "org/geogebra/common/awt/GLine2D.h"
#include "org/geogebra/common/awt/GPaint.h"
#include "org/geogebra/common/awt/GPoint2D.h"
#include "org/geogebra/common/awt/GQuadCurve2D.h"
#include "org/geogebra/common/awt/GRectangle.h"
#include "org/geogebra/common/awt/GRectangle2D.h"
#include "org/geogebra/common/awt/GShape.h"
#include "org/geogebra/common/awt/MyImage.h"
#include "org/geogebra/common/awt/font/GTextLayout.h"
#include "org/geogebra/common/euclidian/event/ActionListener.h"
#include "org/geogebra/common/euclidian/event/ActionListenerI.h"
#include "org/geogebra/common/euclidian/event/FocusListener.h"
#include "org/geogebra/common/factories/AwtFactory.h"

OrgGeogebraCommonFactoriesAwtFactory *OrgGeogebraCommonFactoriesAwtFactory_prototype_ = nil;

@implementation OrgGeogebraCommonFactoriesAwtFactory

- (OrgGeogebraCommonAwtGColor *)newColorWithInt:(jint)RGB {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonAwtGColor *)newColorWithInt:(jint)red
                                        withInt:(jint)green
                                        withInt:(jint)blue {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonAwtGColor *)newColorWithInt:(jint)red
                                        withInt:(jint)green
                                        withInt:(jint)blue
                                        withInt:(jint)alpha {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonAwtGColor *)newColorWithFloat:(jfloat)red
                                        withFloat:(jfloat)green
                                        withFloat:(jfloat)blue
                                        withFloat:(jfloat)alpha {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonAwtGColor *)newColorWithFloat:(jfloat)red
                                        withFloat:(jfloat)green
                                        withFloat:(jfloat)blue {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGAffineTransform>)newAffineTransform {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGRectangle2D>)newRectangle2D {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGRectangle>)newRectangleWithInt:(jint)x
                                                  withInt:(jint)y
                                                  withInt:(jint)w
                                                  withInt:(jint)h {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGBufferedImage>)newBufferedImageWithInt:(jint)pixelWidth
                                                          withInt:(jint)pixelHeight
                                                          withInt:(jint)typeIntArgb {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtMyImage>)newMyImageWithInt:(jint)pixelWidth
                                             withInt:(jint)pixelHeight
                                             withInt:(jint)typeIntArgb {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonAwtGDimension *)newDimensionWithInt:(jint)width
                                                withInt:(jint)height {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonAwtGPoint2D *)newPoint2D {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGRectangle>)newRectangleWithInt:(jint)i
                                                  withInt:(jint)j {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGRectangle>)newRectangle {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonAwtGPoint2D *)newPoint2DWithDouble:(jdouble)d
                                            withDouble:(jdouble)coord {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGGeneralPath>)newGeneralPath {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGBasicStroke>)newMyBasicStrokeWithFloat:(jfloat)f {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGBasicStroke>)newBasicStrokeWithFloat:(jfloat)f
                                                        withInt:(jint)cap
                                                        withInt:(jint)join {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGBasicStroke>)newBasicStrokeWithFloat:(jfloat)width
                                                        withInt:(jint)endCap
                                                        withInt:(jint)lineJoin
                                                      withFloat:(jfloat)miterLimit
                                                 withFloatArray:(IOSFloatArray *)dash
                                                      withFloat:(jfloat)f {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGBasicStroke>)newBasicStrokeWithFloat:(jfloat)f {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGLine2D>)newLine2D {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGRectangle>)newRectangleWithOrgGeogebraCommonAwtGRectangle:(id<OrgGeogebraCommonAwtGRectangle>)bb {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGEllipse2DDouble>)newEllipse2DDouble {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGEllipse2DFloat>)newEllipse2DFloatWithInt:(jint)i
                                                            withInt:(jint)j
                                                            withInt:(jint)k
                                                            withInt:(jint)l {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGArc2D>)newArc2D {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGQuadCurve2D>)newQuadCurve2D {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGArea>)newArea {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGArea>)newAreaWithOrgGeogebraCommonAwtGShape:(id<OrgGeogebraCommonAwtGShape>)shape {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGGeneralPath>)newGeneralPathWithInt:(jint)rule {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGCubicCurve2D>)newCubicCurve2D {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtFontGTextLayout>)newTextLayoutWithNSString:(NSString *)string
                                       withOrgGeogebraCommonAwtGFont:(OrgGeogebraCommonAwtGFont *)fontLine
                          withOrgGeogebraCommonAwtGFontRenderContext:(OrgGeogebraCommonAwtGFontRenderContext *)frc {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGAlphaComposite>)newAlphaCompositeWithInt:(jint)srcOver
                                                          withFloat:(jfloat)alpha {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGBasicStroke>)newBasicStrokeJoinMitreWithFloat:(jfloat)f {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGGradientPaint>)newGradientPaintWithInt:(jint)x
                                                          withInt:(jint)y
                                   withOrgGeogebraCommonAwtGColor:(OrgGeogebraCommonAwtGColor *)bg2
                                                          withInt:(jint)x2
                                                          withInt:(jint)i
                                   withOrgGeogebraCommonAwtGColor:(OrgGeogebraCommonAwtGColor *)bg {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonEuclidianEventFocusListener *)newFocusListenerWithId:(id)listener {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonEuclidianEventActionListener *)newActionListenerWithOrgGeogebraCommonEuclidianEventActionListenerI:(id<OrgGeogebraCommonEuclidianEventActionListenerI>)listener {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtComponent>)newComponentWithId:(id)component {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGPaint>)newTexturePaintWithOrgGeogebraCommonAwtGBufferedImage:(id<OrgGeogebraCommonAwtGBufferedImage>)subimage
                                                     withOrgGeogebraCommonAwtGRectangle:(id<OrgGeogebraCommonAwtGRectangle>)rect {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<OrgGeogebraCommonAwtGPaint>)newTexturePaintWithOrgGeogebraCommonAwtMyImage:(id<OrgGeogebraCommonAwtMyImage>)subimage
                                              withOrgGeogebraCommonAwtGRectangle:(id<OrgGeogebraCommonAwtGRectangle>)rect {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (OrgGeogebraCommonAwtGFont *)newFontWithNSString:(NSString *)name
                                           withInt:(jint)style
                                           withInt:(jint)size {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (instancetype)init {
  OrgGeogebraCommonFactoriesAwtFactory_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "newColorWithInt:", "newColor", "Lorg.geogebra.common.awt.GColor;", 0x401, NULL, NULL },
    { "newColorWithInt:withInt:withInt:", "newColor", "Lorg.geogebra.common.awt.GColor;", 0x401, NULL, NULL },
    { "newColorWithInt:withInt:withInt:withInt:", "newColor", "Lorg.geogebra.common.awt.GColor;", 0x401, NULL, NULL },
    { "newColorWithFloat:withFloat:withFloat:withFloat:", "newColor", "Lorg.geogebra.common.awt.GColor;", 0x401, NULL, NULL },
    { "newColorWithFloat:withFloat:withFloat:", "newColor", "Lorg.geogebra.common.awt.GColor;", 0x401, NULL, NULL },
    { "newAffineTransform", NULL, "Lorg.geogebra.common.awt.GAffineTransform;", 0x401, NULL, NULL },
    { "newRectangle2D", NULL, "Lorg.geogebra.common.awt.GRectangle2D;", 0x401, NULL, NULL },
    { "newRectangleWithInt:withInt:withInt:withInt:", "newRectangle", "Lorg.geogebra.common.awt.GRectangle;", 0x401, NULL, NULL },
    { "newBufferedImageWithInt:withInt:withInt:", "newBufferedImage", "Lorg.geogebra.common.awt.GBufferedImage;", 0x401, NULL, NULL },
    { "newMyImageWithInt:withInt:withInt:", "newMyImage", "Lorg.geogebra.common.awt.MyImage;", 0x401, NULL, NULL },
    { "newDimensionWithInt:withInt:", "newDimension", "Lorg.geogebra.common.awt.GDimension;", 0x401, NULL, NULL },
    { "newPoint2D", NULL, "Lorg.geogebra.common.awt.GPoint2D;", 0x401, NULL, NULL },
    { "newRectangleWithInt:withInt:", "newRectangle", "Lorg.geogebra.common.awt.GRectangle;", 0x401, NULL, NULL },
    { "newRectangle", NULL, "Lorg.geogebra.common.awt.GRectangle;", 0x401, NULL, NULL },
    { "newPoint2DWithDouble:withDouble:", "newPoint2D", "Lorg.geogebra.common.awt.GPoint2D;", 0x401, NULL, NULL },
    { "newGeneralPath", NULL, "Lorg.geogebra.common.awt.GGeneralPath;", 0x401, NULL, NULL },
    { "newMyBasicStrokeWithFloat:", "newMyBasicStroke", "Lorg.geogebra.common.awt.GBasicStroke;", 0x401, NULL, NULL },
    { "newBasicStrokeWithFloat:withInt:withInt:", "newBasicStroke", "Lorg.geogebra.common.awt.GBasicStroke;", 0x401, NULL, NULL },
    { "newBasicStrokeWithFloat:withInt:withInt:withFloat:withFloatArray:withFloat:", "newBasicStroke", "Lorg.geogebra.common.awt.GBasicStroke;", 0x401, NULL, NULL },
    { "newBasicStrokeWithFloat:", "newBasicStroke", "Lorg.geogebra.common.awt.GBasicStroke;", 0x401, NULL, NULL },
    { "newLine2D", NULL, "Lorg.geogebra.common.awt.GLine2D;", 0x401, NULL, NULL },
    { "newRectangleWithOrgGeogebraCommonAwtGRectangle:", "newRectangle", "Lorg.geogebra.common.awt.GRectangle;", 0x401, NULL, NULL },
    { "newEllipse2DDouble", NULL, "Lorg.geogebra.common.awt.GEllipse2DDouble;", 0x401, NULL, NULL },
    { "newEllipse2DFloatWithInt:withInt:withInt:withInt:", "newEllipse2DFloat", "Lorg.geogebra.common.awt.GEllipse2DFloat;", 0x401, NULL, NULL },
    { "newArc2D", NULL, "Lorg.geogebra.common.awt.GArc2D;", 0x401, NULL, NULL },
    { "newQuadCurve2D", NULL, "Lorg.geogebra.common.awt.GQuadCurve2D;", 0x401, NULL, NULL },
    { "newArea", NULL, "Lorg.geogebra.common.awt.GArea;", 0x401, NULL, NULL },
    { "newAreaWithOrgGeogebraCommonAwtGShape:", "newArea", "Lorg.geogebra.common.awt.GArea;", 0x401, NULL, NULL },
    { "newGeneralPathWithInt:", "newGeneralPath", "Lorg.geogebra.common.awt.GGeneralPath;", 0x401, NULL, NULL },
    { "newCubicCurve2D", NULL, "Lorg.geogebra.common.awt.GCubicCurve2D;", 0x401, NULL, NULL },
    { "newTextLayoutWithNSString:withOrgGeogebraCommonAwtGFont:withOrgGeogebraCommonAwtGFontRenderContext:", "newTextLayout", "Lorg.geogebra.common.awt.font.GTextLayout;", 0x401, NULL, NULL },
    { "newAlphaCompositeWithInt:withFloat:", "newAlphaComposite", "Lorg.geogebra.common.awt.GAlphaComposite;", 0x401, NULL, NULL },
    { "newBasicStrokeJoinMitreWithFloat:", "newBasicStrokeJoinMitre", "Lorg.geogebra.common.awt.GBasicStroke;", 0x401, NULL, NULL },
    { "newGradientPaintWithInt:withInt:withOrgGeogebraCommonAwtGColor:withInt:withInt:withOrgGeogebraCommonAwtGColor:", "newGradientPaint", "Lorg.geogebra.common.awt.GGradientPaint;", 0x401, NULL, NULL },
    { "newFocusListenerWithId:", "newFocusListener", "Lorg.geogebra.common.euclidian.event.FocusListener;", 0x401, NULL, NULL },
    { "newActionListenerWithOrgGeogebraCommonEuclidianEventActionListenerI:", "newActionListener", "Lorg.geogebra.common.euclidian.event.ActionListener;", 0x401, NULL, NULL },
    { "newComponentWithId:", "newComponent", "Lorg.geogebra.common.awt.Component;", 0x401, NULL, NULL },
    { "newTexturePaintWithOrgGeogebraCommonAwtGBufferedImage:withOrgGeogebraCommonAwtGRectangle:", "newTexturePaint", "Lorg.geogebra.common.awt.GPaint;", 0x401, NULL, NULL },
    { "newTexturePaintWithOrgGeogebraCommonAwtMyImage:withOrgGeogebraCommonAwtGRectangle:", "newTexturePaint", "Lorg.geogebra.common.awt.GPaint;", 0x401, NULL, NULL },
    { "newFontWithNSString:withInt:withInt:", "newFont", "Lorg.geogebra.common.awt.GFont;", 0x401, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "prototype_", NULL, 0x9, "Lorg.geogebra.common.factories.AwtFactory;", &OrgGeogebraCommonFactoriesAwtFactory_prototype_, NULL,  },
  };
  static const J2ObjcClassInfo _OrgGeogebraCommonFactoriesAwtFactory = { 2, "AwtFactory", "org.geogebra.common.factories", NULL, 0x401, 41, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgGeogebraCommonFactoriesAwtFactory;
}

@end

void OrgGeogebraCommonFactoriesAwtFactory_init(OrgGeogebraCommonFactoriesAwtFactory *self) {
  (void) NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgGeogebraCommonFactoriesAwtFactory)
