//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/geogebra/common/kernel/scripting/CmdTurtleLeft.java
//


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Math.h"
#include "org/geogebra/common/kernel/Kernel.h"
#include "org/geogebra/common/kernel/geos/GeoTurtle.h"
#include "org/geogebra/common/kernel/scripting/CmdTurtleCommand.h"
#include "org/geogebra/common/kernel/scripting/CmdTurtleLeft.h"
#include "org/geogebra/common/main/MyError.h"

@implementation OrgGeogebraCommonKernelScriptingCmdTurtleLeft

- (instancetype)initWithOrgGeogebraCommonKernelKernel:(OrgGeogebraCommonKernelKernel *)kernel {
  OrgGeogebraCommonKernelScriptingCmdTurtleLeft_initWithOrgGeogebraCommonKernelKernel_(self, kernel);
  return self;
}

- (void)performTurtleCommandWithNSString:(NSString *)cname
withOrgGeogebraCommonKernelGeosGeoElementArray:(IOSObjectArray *)args {
  [((OrgGeogebraCommonKernelGeosGeoTurtle *) nil_chk([self getTurtleWithOrgGeogebraCommonKernelGeosGeoElementArray:args])) turnWithDouble:[self getNumArgWithNSString:cname withOrgGeogebraCommonKernelGeosGeoElementArray:args] * 180 / JavaLangMath_PI];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgGeogebraCommonKernelKernel:", "CmdTurtleLeft", NULL, 0x1, NULL, NULL },
    { "performTurtleCommandWithNSString:withOrgGeogebraCommonKernelGeosGeoElementArray:", "performTurtleCommand", "V", 0x4, "Lorg.geogebra.common.main.MyError;", NULL },
  };
  static const J2ObjcClassInfo _OrgGeogebraCommonKernelScriptingCmdTurtleLeft = { 2, "CmdTurtleLeft", "org.geogebra.common.kernel.scripting", NULL, 0x1, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgGeogebraCommonKernelScriptingCmdTurtleLeft;
}

@end

void OrgGeogebraCommonKernelScriptingCmdTurtleLeft_initWithOrgGeogebraCommonKernelKernel_(OrgGeogebraCommonKernelScriptingCmdTurtleLeft *self, OrgGeogebraCommonKernelKernel *kernel) {
  (void) OrgGeogebraCommonKernelScriptingCmdTurtleCommand_initWithOrgGeogebraCommonKernelKernel_(self, kernel);
}

OrgGeogebraCommonKernelScriptingCmdTurtleLeft *new_OrgGeogebraCommonKernelScriptingCmdTurtleLeft_initWithOrgGeogebraCommonKernelKernel_(OrgGeogebraCommonKernelKernel *kernel) {
  OrgGeogebraCommonKernelScriptingCmdTurtleLeft *self = [OrgGeogebraCommonKernelScriptingCmdTurtleLeft alloc];
  OrgGeogebraCommonKernelScriptingCmdTurtleLeft_initWithOrgGeogebraCommonKernelKernel_(self, kernel);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgGeogebraCommonKernelScriptingCmdTurtleLeft)
