//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeogebraiOS/GeogebraiOS/sources/org/geogebra/common/util/NormalizerMinimal.java
//

#ifndef _OrgGeogebraCommonUtilNormalizerMinimal_H_
#define _OrgGeogebraCommonUtilNormalizerMinimal_H_

#include "J2ObjC_header.h"

@interface OrgGeogebraCommonUtilNormalizerMinimal : NSObject

#pragma mark Public

- (instancetype)init;

- (NSString *)transformWithNSString:(NSString *)s;

+ (NSString *)transformStaticWithNSString:(NSString *)s
                              withBoolean:(jboolean)lowerCase;

@end

J2OBJC_STATIC_INIT(OrgGeogebraCommonUtilNormalizerMinimal)

FOUNDATION_EXPORT NSString *OrgGeogebraCommonUtilNormalizerMinimal_transformStaticWithNSString_withBoolean_(NSString *s, jboolean lowerCase);

FOUNDATION_EXPORT void OrgGeogebraCommonUtilNormalizerMinimal_init(OrgGeogebraCommonUtilNormalizerMinimal *self);

FOUNDATION_EXPORT OrgGeogebraCommonUtilNormalizerMinimal *new_OrgGeogebraCommonUtilNormalizerMinimal_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgGeogebraCommonUtilNormalizerMinimal)

#endif // _OrgGeogebraCommonUtilNormalizerMinimal_H_
