//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/apache/commons/math/stat/inference/ChiSquareTest.java
//


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/IllegalArgumentException.h"
#include "org/apache/commons/math/MathException.h"
#include "org/apache/commons/math/stat/inference/ChiSquareTest.h"

@interface OrgApacheCommonsMathStatInferenceChiSquareTest : NSObject
@end

@implementation OrgApacheCommonsMathStatInferenceChiSquareTest

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "chiSquareWithDoubleArray:withLongArray:", "chiSquare", "D", 0x401, "Ljava.lang.IllegalArgumentException;", NULL },
    { "chiSquareTestWithDoubleArray:withLongArray:", "chiSquareTest", "D", 0x401, "Ljava.lang.IllegalArgumentException;Lorg.apache.commons.math.MathException;", NULL },
    { "chiSquareTestWithDoubleArray:withLongArray:withDouble:", "chiSquareTest", "Z", 0x401, "Ljava.lang.IllegalArgumentException;Lorg.apache.commons.math.MathException;", NULL },
    { "chiSquareWithLongArray2:", "chiSquare", "D", 0x401, "Ljava.lang.IllegalArgumentException;", NULL },
    { "chiSquareTestWithLongArray2:", "chiSquareTest", "D", 0x401, "Ljava.lang.IllegalArgumentException;Lorg.apache.commons.math.MathException;", NULL },
    { "chiSquareTestWithLongArray2:withDouble:", "chiSquareTest", "Z", 0x401, "Ljava.lang.IllegalArgumentException;Lorg.apache.commons.math.MathException;", NULL },
  };
  static const J2ObjcClassInfo _OrgApacheCommonsMathStatInferenceChiSquareTest = { 2, "ChiSquareTest", "org.apache.commons.math.stat.inference", NULL, 0x609, 6, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgApacheCommonsMathStatInferenceChiSquareTest;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheCommonsMathStatInferenceChiSquareTest)
