//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/cas/error/TimeoutException.java
//

#ifndef _GeogebraCommonCasErrorTimeoutException_H_
#define _GeogebraCommonCasErrorTimeoutException_H_

#include "J2ObjC_header.h"
#include "geogebra/common/kernel/CASException.h"

@interface GeogebraCommonCasErrorTimeoutException : GeogebraCommonKernelCASException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)message;

- (NSString *)getKey;

@end

J2OBJC_EMPTY_STATIC_INIT(GeogebraCommonCasErrorTimeoutException)

FOUNDATION_EXPORT void GeogebraCommonCasErrorTimeoutException_initWithNSString_(GeogebraCommonCasErrorTimeoutException *self, NSString *message);

FOUNDATION_EXPORT GeogebraCommonCasErrorTimeoutException *new_GeogebraCommonCasErrorTimeoutException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(GeogebraCommonCasErrorTimeoutException)

#endif // _GeogebraCommonCasErrorTimeoutException_H_
