//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/javax/swing/GOptionPane.java
//

#ifndef _GeogebraCommonJavaxSwingGOptionPane_H_
#define _GeogebraCommonJavaxSwingGOptionPane_H_

#include "J2ObjC_header.h"

@class GeogebraCommonMainApp;
@class GeogebraCommonUtilAsyncOperation;
@class IOSObjectArray;

#define GeogebraCommonJavaxSwingGOptionPane_DEFAULT_OPTION -1
#define GeogebraCommonJavaxSwingGOptionPane_OK_CANCEL_OPTION 2
#define GeogebraCommonJavaxSwingGOptionPane_CUSTOM_OPTION 3
#define GeogebraCommonJavaxSwingGOptionPane_OK_OPTION 0
#define GeogebraCommonJavaxSwingGOptionPane_YES_OPTION 0
#define GeogebraCommonJavaxSwingGOptionPane_NO_OPTION 1
#define GeogebraCommonJavaxSwingGOptionPane_CANCEL_OPTION 2
#define GeogebraCommonJavaxSwingGOptionPane_ERROR_MESSAGE 0
#define GeogebraCommonJavaxSwingGOptionPane_INFORMATION_MESSAGE 1
#define GeogebraCommonJavaxSwingGOptionPane_WARNING_MESSAGE 2
#define GeogebraCommonJavaxSwingGOptionPane_QUESTION_MESSAGE 3
#define GeogebraCommonJavaxSwingGOptionPane_PLAIN_MESSAGE -1

@protocol GeogebraCommonJavaxSwingGOptionPane < NSObject, JavaObject >

- (jint)showConfirmDialogWithGeogebraCommonMainApp:(GeogebraCommonMainApp *)app
                                      withNSString:(NSString *)message
                                      withNSString:(NSString *)title
                                           withInt:(jint)optionType
                                           withInt:(jint)messageType
                                            withId:(id)icon;

- (void)showInputDialogWithGeogebraCommonMainApp:(GeogebraCommonMainApp *)app
                                    withNSString:(NSString *)message
                                    withNSString:(NSString *)initialSelectionValue
                                          withId:(id)icon
            withGeogebraCommonUtilAsyncOperation:(GeogebraCommonUtilAsyncOperation *)handler;

- (void)showOptionDialogWithGeogebraCommonMainApp:(GeogebraCommonMainApp *)app
                                     withNSString:(NSString *)message
                                     withNSString:(NSString *)title
                                          withInt:(jint)optionType
                                          withInt:(jint)messageType
                                           withId:(id)icon
                                withNSStringArray:(IOSObjectArray *)optionNames
             withGeogebraCommonUtilAsyncOperation:(GeogebraCommonUtilAsyncOperation *)handler;

- (void)setGlassEnabledWithBoolean:(jboolean)enabled;

@end

J2OBJC_EMPTY_STATIC_INIT(GeogebraCommonJavaxSwingGOptionPane)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, DEFAULT_OPTION, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, OK_CANCEL_OPTION, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, CUSTOM_OPTION, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, OK_OPTION, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, YES_OPTION, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, NO_OPTION, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, CANCEL_OPTION, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, ERROR_MESSAGE, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, INFORMATION_MESSAGE, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, WARNING_MESSAGE, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, QUESTION_MESSAGE, jint)

J2OBJC_STATIC_FIELD_GETTER(GeogebraCommonJavaxSwingGOptionPane, PLAIN_MESSAGE, jint)

J2OBJC_TYPE_LITERAL_HEADER(GeogebraCommonJavaxSwingGOptionPane)

#endif // _GeogebraCommonJavaxSwingGOptionPane_H_
