//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeogebraiOS/GeogebraiOS/sources/org/geogebra/common/geogebra3D/euclidian3D/openGL/GPUBuffers.java
//


#include "J2ObjC_source.h"
#include "org/geogebra/common/geogebra3D/euclidian3D/openGL/GPUBuffers.h"

@interface OrgGeogebraCommonGeogebra3DEuclidian3DOpenGLGPUBuffers : NSObject
@end

@implementation OrgGeogebraCommonGeogebra3DEuclidian3DOpenGLGPUBuffers

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _OrgGeogebraCommonGeogebra3DEuclidian3DOpenGLGPUBuffers = { 2, "GPUBuffers", "org.geogebra.common.geogebra3D.euclidian3D.openGL", NULL, 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgGeogebraCommonGeogebra3DEuclidian3DOpenGLGPUBuffers;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgGeogebraCommonGeogebra3DEuclidian3DOpenGLGPUBuffers)
