//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/kernel/scripting/CmdStartAnimation.java
//

#ifndef _GeogebraCommonKernelScriptingCmdStartAnimation_H_
#define _GeogebraCommonKernelScriptingCmdStartAnimation_H_

#include "J2ObjC_header.h"
#include "geogebra/common/kernel/commands/CmdScripting.h"

@class GeogebraCommonKernelArithmeticCommand;
@class GeogebraCommonKernelKernel;

@interface GeogebraCommonKernelScriptingCmdStartAnimation : GeogebraCommonKernelCommandsCmdScripting

#pragma mark Public

- (instancetype)initWithGeogebraCommonKernelKernel:(GeogebraCommonKernelKernel *)kernel;

#pragma mark Protected

- (void)performWithGeogebraCommonKernelArithmeticCommand:(GeogebraCommonKernelArithmeticCommand *)c;

@end

J2OBJC_EMPTY_STATIC_INIT(GeogebraCommonKernelScriptingCmdStartAnimation)

FOUNDATION_EXPORT void GeogebraCommonKernelScriptingCmdStartAnimation_initWithGeogebraCommonKernelKernel_(GeogebraCommonKernelScriptingCmdStartAnimation *self, GeogebraCommonKernelKernel *kernel);

FOUNDATION_EXPORT GeogebraCommonKernelScriptingCmdStartAnimation *new_GeogebraCommonKernelScriptingCmdStartAnimation_initWithGeogebraCommonKernelKernel_(GeogebraCommonKernelKernel *kernel) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(GeogebraCommonKernelScriptingCmdStartAnimation)

#endif // _GeogebraCommonKernelScriptingCmdStartAnimation_H_
