//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/apache/commons/collections15/collection/AbstractCollectionDecorator.java
//

#ifndef _OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator_H_
#define _OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator_H_

#include "J2ObjC_header.h"
#include "java/util/Collection.h"

@class IOSObjectArray;
@protocol JavaUtilIterator;

@interface OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator : NSObject < JavaUtilCollection > {
 @public
  id<JavaUtilCollection> collection_;
}

#pragma mark Public

- (jboolean)addWithId:(id)object;

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)coll;

- (void)clear;

- (jboolean)containsWithId:(id)object;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)coll;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (jboolean)isEmpty;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)object;

- (jboolean)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)coll;

- (jboolean)retainAllWithJavaUtilCollection:(id<JavaUtilCollection>)coll;

- (jint)size;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)object;

- (NSString *)description;

#pragma mark Protected

- (instancetype)init;

- (instancetype)initWithJavaUtilCollection:(id<JavaUtilCollection>)coll;

- (id<JavaUtilCollection>)getCollection;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator)

J2OBJC_FIELD_SETTER(OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator, collection_, id<JavaUtilCollection>)

FOUNDATION_EXPORT void OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator_init(OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator *self);

FOUNDATION_EXPORT void OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator_initWithJavaUtilCollection_(OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator *self, id<JavaUtilCollection> coll);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator)

#endif // _OrgApacheCommonsCollections15CollectionAbstractCollectionDecorator_H_
