//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/com/vividsolutions/jts/geom/util/GeometryTransformer.java
//

#ifndef _ComVividsolutionsJtsGeomUtilGeometryTransformer_H_
#define _ComVividsolutionsJtsGeomUtilGeometryTransformer_H_

#include "J2ObjC_header.h"

@class ComVividsolutionsJtsGeomGeometry;
@class ComVividsolutionsJtsGeomGeometryCollection;
@class ComVividsolutionsJtsGeomGeometryFactory;
@class ComVividsolutionsJtsGeomLineString;
@class ComVividsolutionsJtsGeomLinearRing;
@class ComVividsolutionsJtsGeomMultiLineString;
@class ComVividsolutionsJtsGeomMultiPoint;
@class ComVividsolutionsJtsGeomMultiPolygon;
@class ComVividsolutionsJtsGeomPoint;
@class ComVividsolutionsJtsGeomPolygon;
@class IOSObjectArray;
@protocol ComVividsolutionsJtsGeomCoordinateSequence;

@interface ComVividsolutionsJtsGeomUtilGeometryTransformer : NSObject {
 @public
  ComVividsolutionsJtsGeomGeometryFactory *factory_;
}

#pragma mark Public

- (instancetype)init;

- (ComVividsolutionsJtsGeomGeometry *)getInputGeometry;

- (ComVividsolutionsJtsGeomGeometry *)transformWithComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)inputGeom;

#pragma mark Protected

- (id<ComVividsolutionsJtsGeomCoordinateSequence>)copy__WithComVividsolutionsJtsGeomCoordinateSequence:(id<ComVividsolutionsJtsGeomCoordinateSequence>)seq OBJC_METHOD_FAMILY_NONE;

- (id<ComVividsolutionsJtsGeomCoordinateSequence>)createCoordinateSequenceWithComVividsolutionsJtsGeomCoordinateArray:(IOSObjectArray *)coords;

- (id<ComVividsolutionsJtsGeomCoordinateSequence>)transformCoordinatesWithComVividsolutionsJtsGeomCoordinateSequence:(id<ComVividsolutionsJtsGeomCoordinateSequence>)coords
                                                                                withComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)parent;

- (ComVividsolutionsJtsGeomGeometry *)transformGeometryCollectionWithComVividsolutionsJtsGeomGeometryCollection:(ComVividsolutionsJtsGeomGeometryCollection *)geom
                                                                           withComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)parent;

- (ComVividsolutionsJtsGeomGeometry *)transformLinearRingWithComVividsolutionsJtsGeomLinearRing:(ComVividsolutionsJtsGeomLinearRing *)geom
                                                           withComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)parent;

- (ComVividsolutionsJtsGeomGeometry *)transformLineStringWithComVividsolutionsJtsGeomLineString:(ComVividsolutionsJtsGeomLineString *)geom
                                                           withComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)parent;

- (ComVividsolutionsJtsGeomGeometry *)transformMultiLineStringWithComVividsolutionsJtsGeomMultiLineString:(ComVividsolutionsJtsGeomMultiLineString *)geom
                                                                     withComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)parent;

- (ComVividsolutionsJtsGeomGeometry *)transformMultiPointWithComVividsolutionsJtsGeomMultiPoint:(ComVividsolutionsJtsGeomMultiPoint *)geom
                                                           withComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)parent;

- (ComVividsolutionsJtsGeomGeometry *)transformMultiPolygonWithComVividsolutionsJtsGeomMultiPolygon:(ComVividsolutionsJtsGeomMultiPolygon *)geom
                                                               withComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)parent;

- (ComVividsolutionsJtsGeomGeometry *)transformPointWithComVividsolutionsJtsGeomPoint:(ComVividsolutionsJtsGeomPoint *)geom
                                                 withComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)parent;

- (ComVividsolutionsJtsGeomGeometry *)transformPolygonWithComVividsolutionsJtsGeomPolygon:(ComVividsolutionsJtsGeomPolygon *)geom
                                                     withComVividsolutionsJtsGeomGeometry:(ComVividsolutionsJtsGeomGeometry *)parent;

@end

J2OBJC_EMPTY_STATIC_INIT(ComVividsolutionsJtsGeomUtilGeometryTransformer)

J2OBJC_FIELD_SETTER(ComVividsolutionsJtsGeomUtilGeometryTransformer, factory_, ComVividsolutionsJtsGeomGeometryFactory *)

FOUNDATION_EXPORT void ComVividsolutionsJtsGeomUtilGeometryTransformer_init(ComVividsolutionsJtsGeomUtilGeometryTransformer *self);

FOUNDATION_EXPORT ComVividsolutionsJtsGeomUtilGeometryTransformer *new_ComVividsolutionsJtsGeomUtilGeometryTransformer_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComVividsolutionsJtsGeomUtilGeometryTransformer)

#endif // _ComVividsolutionsJtsGeomUtilGeometryTransformer_H_
