//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/geogebra/common/kernel/kernelND/SurfaceEvaluable.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "org/geogebra/common/kernel/Kernel.h"
#include "org/geogebra/common/kernel/Matrix/Coords.h"
#include "org/geogebra/common/kernel/Matrix/Coords3.h"
#include "org/geogebra/common/kernel/kernelND/SurfaceEvaluable.h"

@interface OrgGeogebraCommonKernelKernelNDSurfaceEvaluable : NSObject
@end

__attribute__((unused)) static void OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initWithNSString_withInt_(OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum *new_OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

@implementation OrgGeogebraCommonKernelKernelNDSurfaceEvaluable

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "evaluatePointWithDouble:withDouble:", "evaluatePoint", "Lorg.geogebra.common.kernel.Matrix.Coords;", 0x401, NULL, NULL },
    { "evaluatePointWithDouble:withDouble:withOrgGeogebraCommonKernelMatrixCoords3:", "evaluatePoint", "V", 0x401, NULL, NULL },
    { "evaluateNormalWithOrgGeogebraCommonKernelMatrixCoords3:withDouble:withDouble:withOrgGeogebraCommonKernelMatrixCoords3:", "evaluateNormal", "Z", 0x401, NULL, NULL },
    { "getMinParameterWithInt:", "getMinParameter", "D", 0x401, NULL, NULL },
    { "getMaxParameterWithInt:", "getMaxParameter", "D", 0x401, NULL, NULL },
    { "setDerivatives", NULL, "V", 0x401, NULL, NULL },
    { "resetDerivatives", NULL, "V", 0x401, NULL, NULL },
    { "getLevelOfDetail", NULL, "Lorg.geogebra.common.kernel.kernelND.SurfaceEvaluable$LevelOfDetail;", 0x401, NULL, NULL },
    { "setLevelOfDetailWithOrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum:", "setLevelOfDetail", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "NUMERICAL_DELTA_", NULL, 0x19, "D", NULL, NULL, .constantValue.asDouble = OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_NUMERICAL_DELTA },
  };
  static const char *inner_classes[] = {"Lorg.geogebra.common.kernel.kernelND.SurfaceEvaluable$LevelOfDetail;"};
  static const J2ObjcClassInfo _OrgGeogebraCommonKernelKernelNDSurfaceEvaluable = { 2, "SurfaceEvaluable", "org.geogebra.common.kernel.kernelND", NULL, 0x609, 9, methods, 1, fields, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_OrgGeogebraCommonKernelKernelNDSurfaceEvaluable;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgGeogebraCommonKernelKernelNDSurfaceEvaluable)

J2OBJC_INITIALIZED_DEFN(OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum)

OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum *OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_values_[2];

@implementation OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_values() {
  OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initialize();
  return [IOSObjectArray arrayWithObjects:OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_values_ count:2 type:OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_class_()];
}

+ (IOSObjectArray *)values {
  return OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_values();
}

+ (OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum *)valueOfWithNSString:(NSString *)name {
  return OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_valueOfWithNSString_(name);
}

OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum *OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_valueOfWithNSString_(NSString *name) {
  OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initialize();
  for (int i = 0; i < 2; i++) {
    OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum *e = OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (void)initialize {
  if (self == [OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum class]) {
    OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_SPEED = new_OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initWithNSString_withInt_(@"SPEED", 0);
    OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_QUALITY = new_OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initWithNSString_withInt_(@"QUALITY", 1);
    J2OBJC_SET_INITIALIZED(OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "SPEED", "SPEED", 0x4019, "Lorg.geogebra.common.kernel.kernelND.SurfaceEvaluable$LevelOfDetail;", &OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_SPEED, NULL,  },
    { "QUALITY", "QUALITY", 0x4019, "Lorg.geogebra.common.kernel.kernelND.SurfaceEvaluable$LevelOfDetail;", &OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_QUALITY, NULL,  },
  };
  static const char *superclass_type_args[] = {"Lorg.geogebra.common.kernel.kernelND.SurfaceEvaluable$LevelOfDetail;"};
  static const J2ObjcClassInfo _OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum = { 2, "LevelOfDetail", "org.geogebra.common.kernel.kernelND", "SurfaceEvaluable", 0x4019, 0, NULL, 2, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lorg/geogebra/common/kernel/kernelND/SurfaceEvaluable$LevelOfDetail;>;" };
  return &_OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum;
}

@end

void OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initWithNSString_withInt_(OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum *self, NSString *__name, jint __ordinal) {
  (void) JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum *new_OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum *self = [OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum alloc];
  OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgGeogebraCommonKernelKernelNDSurfaceEvaluable_LevelOfDetailEnum)
