//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/geogebra_iOS/geogebra/geogebra/common/src/geogebra/common/geogebra3D/euclidian3D/Hits3D.java
//

#ifndef _GeogebraCommonGeogebra3DEuclidian3DHits3D_H_
#define _GeogebraCommonGeogebra3DEuclidian3DHits3D_H_

#include "J2ObjC_header.h"
#include "geogebra/common/euclidian/Hits.h"

@class GeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D;
@class GeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer_PickingTypeEnum;
@class GeogebraCommonKernelGeosGeoElement;
@class JavaUtilArrayList;

@interface GeogebraCommonGeogebra3DEuclidian3DHits3D : GeogebraCommonEuclidianHits

#pragma mark Public

- (instancetype)init;

- (jboolean)addWithId:(GeogebraCommonKernelGeosGeoElement *)geo;

- (void)addDrawable3DWithGeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D:(GeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D *)d
     withGeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer_PickingTypeEnum:(GeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer_PickingTypeEnum *)type;

- (void)addDrawable3DWithGeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D:(GeogebraCommonGeogebra3DEuclidian3DDrawDrawable3D *)d
     withGeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer_PickingTypeEnum:(GeogebraCommonGeogebra3DEuclidian3DOpenGLRenderer_PickingTypeEnum *)type
                                                                withDouble:(jdouble)zNear
                                                                withDouble:(jdouble)zFar;

- (GeogebraCommonGeogebra3DEuclidian3DHits3D *)clone;

- (JavaUtilArrayList *)getDrawables;

- (GeogebraCommonKernelGeosGeoElement *)getLabelHit;

- (GeogebraCommonEuclidianHits *)getTopHits;

- (GeogebraCommonEuclidianHits *)getTopHitsWithInt:(jint)depth
                                           withInt:(jint)geoN;

- (void)init__ OBJC_METHOD_FAMILY_NONE;

- (void)removeAllPolygonsAndQuadricsButOne;

- (void)removeAllPolygonsButOne;

- (void)sort;

#pragma mark Protected

- (GeogebraCommonEuclidianHits *)createNewHits;

- (GeogebraCommonEuclidianHits *)newHits OBJC_METHOD_FAMILY_NONE;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(GeogebraCommonGeogebra3DEuclidian3DHits3D)

FOUNDATION_EXPORT void GeogebraCommonGeogebra3DEuclidian3DHits3D_init(GeogebraCommonGeogebra3DEuclidian3DHits3D *self);

FOUNDATION_EXPORT GeogebraCommonGeogebra3DEuclidian3DHits3D *new_GeogebraCommonGeogebra3DEuclidian3DHits3D_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(GeogebraCommonGeogebra3DEuclidian3DHits3D)

#endif // _GeogebraCommonGeogebra3DEuclidian3DHits3D_H_
